### ISSUE TITLE
Question with localSubpath

### ISSUE THREAD

**Issue by brian91dd** [isaachinman/next-i18next#472] opened 2019-08-26 21:09 UTC
I have this situation.

the site default language is in English, so if you access mysite.com/ it has to be in English.

then there is a version in Spanish and the URL has to look like this mysite.com/es

when I try to enter mysite.com/  it keeps redirecting to mysite.com/en ... How can I prevent that redirection only for the default language?

This is the configuration

``` javascript
module.exports = new NextI18Next({
    defaultLanguage: 'en',
    otherLanguages: ['es'],
    localeSubpaths: {
        en: 'en',
        es: 'es',
    },
});
```

also tried this

``` javascript
module.exports = new NextI18Next({
    defaultLanguage: 'en',
    otherLanguages: ['es'],
    localeSubpaths: {
        en: '',
        es: 'es',
    },
});
```

and this

``` javascript
module.exports = new NextI18Next({
    defaultLanguage: 'en',
    otherLanguages: ['es'],
    localeSubpaths: {
        es: 'es',
    },
});
```

**Comment by isaachinman** [comment] 2019-08-26 21:21
Simply omit that locale. The third code block should work.

**Comment by StarpTech** [comment] 2019-08-27 13:23
@isaachinman if we omit the locale then it [results](https://github.com/isaachinman/next-i18next/blob/master/src/middlewares/next-i18next-middleware.ts#L22) in a wrong regex -> 404
If we add all locales to `localeSubpaths` the `defaultLanguage` doesn't work anymore. There is a huge bug in the redirection logic.

**Comment by isaachinman** [comment] 2019-08-27 17:30
> if we omit the locale

What exactly does this mean? The logic is relatively simple:

```jsx
Object.values(localeSubpaths)
```

**Comment by StarpTech** [comment] 2019-08-27 19:48
@isaachinman if you provide only one subLocale `de` and `defaultLanguage` e.g "en" the regex will look like `/:subpath(de)(.*)`. If you go to `http://localhost:8082/en` will result in 404 because the request is skipped. If you pass two sub locales `de` and `en` the middleware will redirect it but the `defaultLanguage` no longer works because `subpathIsRequired` will always return `true`.

**Comment by isaachinman** [comment] 2019-08-27 20:08
> if you provide only one localeSubpath de [...] [and] you go to http://localhost:8082/en will result in 404

That's exactly right. That is the expected behaviour.

In reality, we probably need to do away with the concept of "default" and "other" languages as we're not doing anything special with them anymore.

**Comment by StarpTech** [comment] 2019-08-27 20:34
@isaachinman and how do I archive the default behaviour? `localhost:8082/` loads `defaultLanguage`?

**Comment by isaachinman** [comment] 2019-08-27 20:35
What do you mean, archive? This package no longer does any `localeSubpath` "magic" - you have to provide the strings for each subpath that you want.

**Comment by StarpTech** [comment] 2019-08-27 20:44
`localhost:8082` should load my default language but `localhost:8082/locale` the specific language. How do I archive that? That was the good old implementation from version 0.x.

**Comment by StarpTech** [comment] 2019-08-27 21:21
I think I got it. @isaachinman there is no longer the case that `localhost:8082/` can point to the default locale. Either it will point directly to `/de` or `/en` with subpath settings: `{ en: 'en', de: 'de',}` or the language is detected by browser, cookie and the middleware will redirect you to the appropriate sub path.

**Comment by isaachinman** [comment] 2019-08-28 18:39
Yes, that's correct. This is the least opinionated approach I could come up with. Frankly it's a never-ending story to support locale subpaths, as every business wants to do it "their way". Hopefully this is a solution that most people can make work, with a little fiddling.

**Comment by isaachinman** [comment] 2019-08-31 10:30
Closing now as I think this has been discussed enough, let me know if not.

**Closed by isaachinman** 2019-08-31 10:30 UTC

**Comment by stevewillard** [comment] 2019-09-13 15:26
@brian91dd did you figure out your issue? I'm having the same problem where my app redirects the page to /es and that isn't the default one.
