### ISSUE TITLE
"ReactDOMServer does not yet support Suspense." - message on projects start on nextjs

### ISSUE THREAD

**Issue by Ceditvodu** [isaachinman/next-i18next#1255] opened 2021-06-13 18:59 UTC
## 🐛 Bug Report

On start nextjs shows error with next text: 
"ReactDOMServer does not yet support Suspense."
And after a two seconds it is renders the page with correct translation.

### Screen of error:
<img width="1021" alt="image" src="https://user-images.githubusercontent.com/8017544/121814369-5559f500-cc79-11eb-9c99-611d2d14bab5.png">

## To Reproduce

Test translation files serves with [http-server](https://www.npmjs.com/package/http-server)

There is a code example on code sandbox: 
[example](https://codesandbox.io/s/next-server-localization-gh6bj?file=/next-i18next.config.js:458-487)

the structure on a server is next: 

- \ ru 
   | - header.json
- \ ua
   | - header.json
- \ pl
   | - header.json

### translation file content (header.json)
```json
{
  "warenyky": "вареники"
}
```
   
### next-i18next.config.js
```js
const I18nextChainedBackend = require('i18next-chained-backend/dist/cjs/i18nextChainedBackend');
const I18NextHttpBackend = require('i18next-http-backend/cjs');

module.exports = {
  debug: true,
  i18n: {
    defaultLocale: 'ru',
    locales: ['ru', 'ua', 'pl'],
  },
  serializeConfig: false,
  use: [I18nextChainedBackend],
  backend: {
    backends: [
      I18NextHttpBackend,
    ],
    backendOptions: [
      {
        loadPath: 'https://9b67ef78f276.ngrok.io/{{lng}}/{{ns}}.json',
        crossDomain: true,
        requestOptions: {
          mode: 'no-cors',
          cache: 'default',
        },
      },
    ],
  },
};
```

### next.config.js
```js
const { i18n } = require('./next-i18next.config')

module.exports = {
  i18n,
};
```

### _app.tsx
```tsx
import type { AppProps, AppContext } from 'next/app';
import { appWithTranslation } from 'next-i18next'
import { reduxWrapper } from 'store';
import Head from 'next/head';
import nextI18NextConfig from '../next-i18next.config';

function MyApp({ Component, pageProps }: AppProps | any) {
  return (
    <>
      <Head>
        <title>some title</title>
      </Head>
        <Component {...pageProps} />
    </>
  );
}

MyApp.getInitialProps = async ({ Component, ctx }: AppContext) => {
  const pageProps = Component.getInitialProps
    ? await Component.getInitialProps(ctx)
    : {};
  return { pageProps: pageProps };
};

export default reduxWrapper.withRedux(appWithTranslation(MyApp, nextI18NextConfig));
```

### page.tsx
```tsx
import Head from 'next/head';
import React from 'react';
import { serverSideTranslations } from 'next-i18next/serverSideTranslations';
import { GetServerSideProps } from 'next';
import nextI18NextConfig from '../next-i18next.config.js';
import TargetComponent from '@components/TargetComponent';

const Page = (props) => {
  return (
    <>
      <Head>
        <title>page</title>
      </Head>
      <TargetComponent>content</TargetComponent>
    </>
  );
};

export const getServerSideProps: GetServerSideProps = async ({
  locale,
}: any) => {
  return {
    props: {
      ...(await serverSideTranslations(locale, ['header'], nextI18NextConfig)),
    },
  };
};

export default Page;
```

### TargetComponent.tsx
```tsx
import { useTranslation } from 'next-i18next';
import React from 'react';

export const TargetComponent = function (props) {
  const [t, i18n, ready] = useTranslation('example', { 
    useSuspense: false 
  });
  console.log('ready', ready, i18n,  i18n.getResourceBundle(i18n.language, 'header'));
  return (
    <div>
      {ready ? t('warenyky'): 'loading'}
    </div>
  );
};
```

## Expected behavior

The possibility to use backend stored translations with `next-i18next`, `i18next-http-backend` and `i18next-chained-backend` without "Suspense" error.

## Environment

- *runtime version*:  node v14, safari
- *next-i18next version*: 8.4.0
- *i18next-http-backend version*: 1.2.6
- *i18next-chained-backend version*: 3.0.2
- *next version*: 10.2.3
- *os*: Mac

**Comment by isaachinman** [comment] 2021-06-13 19:18
Have you debugged the issue? What is using suspense, thus causing the error? Most likely this is simply user error, and you just need to modify values in your i18next config.

**Comment by Ceditvodu** [comment] 2021-06-13 19:54
@isaachinman 

In console I see same error as described

<img width="952" alt="image" src="https://user-images.githubusercontent.com/8017544/121820167-040e2d80-cc9a-11eb-8a2f-eb07faefde30.png">

and another weird message: 

<img width="616" alt="image" src="https://user-images.githubusercontent.com/8017544/121820184-2142fc00-cc9a-11eb-81f9-411c110fcf52.png">

i18next: init: i18next is already initialized. You should call init just once!

The code itself not complicate
you can check it on a sandbox [example](https://codesandbox.io/s/next-server-localization-gh6bj?file=/next-i18next.config.js:458-487)

**Comment by Ceditvodu** [comment] 2021-06-13 19:58
also it seems like it could be reproduced only on server start, on page refresh it won't appear

**Comment by Ceditvodu** [comment] 2021-06-14 18:11
@isaachinman maybe you know which value I can try to modify in config? Because I've try a lot of them before and nothing help...

**Comment by siddhantk232** [comment] 2021-06-15 08:45
I am getting the same error but it does not go away on page reload in my case. I have followed all the steps from the docs. This error comes up when I call `serverSideTranslations` from my nextjs pages. I tried to log the result of this function and it works as expected. Perhaps the `appWithTranslation` is causing issues. I tried both webpack 4 and 5.

**Comment by virgilbugnariu** [comment] 2021-06-15 14:35
I've been experiencing this as well. Updated to the latest versions and it's still reproducing. Just to make sure, are there any known issues with next 10.2.x?

**Comment by isaachinman** [comment] 2021-06-15 14:40
Could be a duplicate of #1202.

**Comment by RA80533** [comment] 2021-06-18 10:47
@isaachinman Not related to the issue. The OP of this thread is experiencing this problem with both Webpack 4 and Webpack 5.

The issue you linked is related to Webpack 5 not transpiling a file incorrectly loaded via `import`.

**Comment by BennettDixon** [comment] 2021-06-18 17:02
I encountered this issue today as well. I was able to solve it by adding the following build settings to my `next-i18next.config.js` file:

```
react: {
    useSuspense: false
}
```

I found the solution in the NextJS Github repository issues section here: https://github.com/vercel/next.js/issues/22508#issuecomment-791205161

**Comment by isaachinman** [comment] 2021-06-20 08:21
@jamuhl @adrai What is the expected value for `react.useSuspense` these days? Should we change the [default value](https://github.com/isaachinman/next-i18next/blob/master/src/config/defaultConfig.ts#L28) to `false`?

**Comment by adrai** [comment] 2021-06-20 08:43
When translations are loaded asynchronously (i.e. when using i18next-http-backend or any other async backend) react-i18next (since v10) by default assumes you can use Suspense. If Suspense can't be used, you need to set useSuspense to false.
Generally when not using Suspense, you should wait for the ready flag to be true: https://react.i18next.com/latest/usetranslation-hook#not-using-suspense or https://react.i18next.com/latest/withtranslation-hoc#not-using-suspense
![image](https://user-images.githubusercontent.com/1086194/122667590-deaa8380-d1b3-11eb-974e-3bee0121613f.png)
![image](https://user-images.githubusercontent.com/1086194/122667633-19acb700-d1b4-11eb-81c4-82d58b5b123b.png)

![image](https://user-images.githubusercontent.com/1086194/122667608-ff72d900-d1b3-11eb-9441-a644995fb178.png)
![image](https://user-images.githubusercontent.com/1086194/122667624-0ef22200-d1b4-11eb-8f3c-b276d6071b15.png)


Since it seemed Suspense was not supported in SSR apps, this was the advice we've written in the react-i18next documentation: https://react.i18next.com/latest/ssr#passing-initial-translations-initial-language-down-to-client

**Comment by isaachinman** [comment] 2021-06-20 09:07
@adrai We recommend users declare namespaces per-page. Is there any drawback to `useSuspense: false`? Is it not enough to [await the init promise](https://github.com/isaachinman/next-i18next/blob/master/src/createClient/node.ts#L28)?

**Comment by adrai** [comment] 2021-06-20 09:09
If the namespaces (and languages) are not preloaded (defined) on init(), they will be lacy loaded, this will trigger a suspense or if nit using suspense, the user neeeds to check the ready flag, else the translations will not be ready to render...

**Comment by artooras** [comment] 2021-07-05 17:34
I've been trying to piece together all the advice on this issue, but I'm still hopelessly stuck... Perhaps a keen eye will spot my mistake. Here's my setup:

**next.config.js**
```
const {i18n} = require('./next-i18next.config')

module.exports = {
  i18n,
  reactStrictMode: true
}

```

**next-i18next.config.js**
```
module.exports = {
  i18n: {
    defaultLocale: 'en',
    locales: ['en', 'de']
  },
  react: {
    useSuspense: false,
    wait: true
  },
  ns: ['common']
}
```

My translations are located at
```
public
  locales
    en
      common.js
```

I only have these pages so far:
```
pages
  _app.js
  _document.js
  index.tsx

```

**_app.js**
```
import {appWithTranslation} from 'next-i18next'
import {createGlobalStyle, ThemeProvider} from 'styled-components'
import theme, {globalStyle} from 'utils/theme'

const GlobalStyle = createGlobalStyle`${globalStyle}`

const MyApp = ({Component, pageProps}) => (
  <ThemeProvider theme={theme}>
    <GlobalStyle />
    <Component {...pageProps} />
  </ThemeProvider>
)

export default appWithTranslation(MyApp)
```

**_document.js**
An exact copy of [this](https://github.com/vercel/next.js/blob/master/examples/with-styled-components/pages/_document.js).

**index.tsx**
```
import React from 'react'
import styled from 'styled-components'
import {useTranslation} from 'next-i18next'
import {serverSideTranslations} from 'next-i18next/serverSideTranslations'

const Container = styled.div`...`

const Index = () => {
  const {t} = useTranslation()
  return (
    <Container>
      <h1>{t('index.intro')}</h1>
      ...
    </Container>
  )
}

export const getStaticProps = async ({locale}) => ({
  props: {
    ...await serverSideTranslations(locale, ['common'])
  }
})

export default Index
```

BTW, I'm getting the `Error: ReactDOMServer does not yet support Suspense.` message in **_document.js** here:
![image](https://user-images.githubusercontent.com/4358143/124504240-ba63bf00-ddcf-11eb-88e9-35efdd3fe8f1.png)

Although, it's fair to say that I started receiving this error since I added **next-i18next** as styled-components (with `_document.js` as it is now) worked well before.

Here are also my dependencies in **packages.json** 
```
"dependencies": {
    "next": "11.0.1",
    "next-i18next": "^8.5.1",
    "react": "17.0.2",
    "react-dom": "17.0.2",
    "styled-components": "^5.3.0"
  },
  "devDependencies": {
    "@types/styled-components": "^5.1.11",
    "babel-plugin-styled-components": "^1.13.1",
    "eslint": "7.30.0",
    "eslint-config-next": "11.0.1",
    "typescript": "^4.3.5"
  }
```

I'd appreciate any help on this!

**Comment by huarmenta** [comment] 2021-08-19 17:41
PROBLEM: In my case the issue was that i didn't have any locale.json referring to the locale I was loading in serverSideTranslations.
SOLUTION: I just added a new locale file with the name I was trying to load and everything worked fine. 

I know it's kind of dumb but maybe someone may find this helpful.

**Closed** 2021-11-16 10:50 UTC

**Comment by stevenfukase** [comment] 2021-12-08 06:14
Fixed it by using the correct namespace

I was doing:
```
const { t } = useTranslation('members');
{t('loading_session')}
```
Instead of:
```
const { t } = useTranslation('common');
{t('members.loading_session')}
```
