### ISSUE TITLE
Unable to find user config when deploying to AWS using serverless

### ISSUE THREAD

**Issue by poppein** [isaachinman/next-i18next#1056] opened 2021-03-11 15:12 UTC
## Describe the bug
When pushing my application to AWS, the lambda executed for SSR raises the following error : 

`next-i18next was unable to find a user config`

That seems to be connected to the next-i18next.config.js file not being there. I am building the app using serverless and when i inspect what's being built, i can't indeed find this file in the bundle. I also realized that each language sub path ends up raising a 404. The bundle actually contains a 404.html page in each language folder generated.

## Occurs in next-i18next version
8.1.0

## Steps to reproduce
The code i am using is standard. I am using `getServerSideProps` with `serverSideTranslations` for the 2 pages i have in my app. Everything works fine on localhost. Problem is happening only when bundling to AWS

**Comment by isaachinman** [comment] 2021-03-11 15:16
Duplicate of #990.

**Closed by isaachinman** 2021-03-11 15:16 UTC

**Comment by janpaepke** [comment] 2021-11-12 16:18
Hi Isaac,

I actually think this is not a duplicate.

The error in #990 is `Error: appWithTranslation was called without a next-i18next config`.  
This one is `next-i18next was unable to find a user config`, which I have actually also just encountered.

Following #990 sent me in the wrong direction, so I'm leaving this here in case this happens to someone else as well.  
In my case the solution was that the optimised deployment image was not copying over the config files.

This is actually mentioned in the docs at the very bottom: https://github.com/isaachinman/next-i18next#notes  
So this was a classic case of rtfm and adding those two lines to my docker file resolved the issue.

Hope this helps someone.

All the best,
Jan
