### ISSUE TITLE
Support for react18/next concurrentFeatures and edge.

### ISSUE THREAD

**Issue by Joelgullander** [isaachinman/next-i18next#1533] opened 2021-11-16 23:35 UTC
Could not find any current issues about supporting the concurrentFeature flag in nextjs related to the react18 beta release. The `fs` scope can't be used in edge runtimes. 

```
export const getStaticProps: GetStaticProps = async({ locale }) => ({
  props: {
    ...(await serverSideTranslations(locale as string, [
      'common',
      'confirmation',
      'delivery'
    ]))
  }
})
```

**Errors:**
```
error - ./node_modules/next-i18next/dist/commonjs/serverSideTranslations.js
Module not found: Can't resolve 'fs' in '/Users/joelgullander/XXXX/XXXX/XXXX.XXX/node_modules/next-i18next/dist/commonjs'
Native Node.js APIs are not supported in the Edge Runtime with `concurrentFeatures` enabled. Found `fs` imported.
```

**Comment by isaachinman** [comment] 2021-11-17 11:01
Duplicate of #1519, although thanks for a more accurate title.

The `next-i18next` package does not aim to support _any_ NextJs experimental features. That said, migrating the `fs` calls to `import` as mentioned [here](https://github.com/isaachinman/next-i18next/issues/935#issuecomment-970035552) may resolve the issue.

I won't be actively working on support until actual stable releases land, but PRs are always welcome!

**Closed by isaachinman** 2021-11-17 11:01 UTC

**Comment by milad-afkhami** [comment] 2022-12-24 14:07
> Duplicate of #1519, although thanks for a more accurate title.
> 
> The `next-i18next` package does not aim to support _any_ NextJs experimental features. That said, migrating the `fs` calls to `import` as mentioned [here](https://github.com/isaachinman/next-i18next/issues/935#issuecomment-970035552) may resolve the issue.
> 
> I won't be actively working on support until actual stable releases land, but PRs are always welcome!

Edge runtime is now stable via adding `export const config = { runtime: 'edge' };` to `next.config.js`.

_"experimental-"_ prefix is no longer needed.

[Next.js 13.1 release](https://nextjs.org/blog/next-13-1#a-light-nodejs-runtime-for-the-edge-now-stable-for-api-routes)

**Comment by adrai** [comment] 2022-12-24 14:16
@milad-afkhami next-i18next depends on the Node.js fs and path module: https://github.com/i18next/next-i18next/blob/master/src/serverSideTranslations.ts#L1
Maybe the approach without next-i18next for app dir setup is an alternative? https://locize.com/blog/next-13-app-dir-i18n/

**Comment by milad-afkhami** [comment] 2022-12-24 15:34
@adrai 

But I love the way `next-i18next` is managing my _i18n_ configuration 🥺

should I wait for maintainers to support edge runtime or should I move on to alternative solutions?

**Comment by adrai** [comment] 2022-12-24 16:01
As long as it depends on the fs module it will not work

**Comment by milad-afkhami** [comment] 2022-12-25 05:44
@adrai
Thanks for the quick response

Now that the edge runtime is stable, people are going to use it more often. so you should probably mention that in the docs.
