### ISSUE TITLE
Multiple cookies are created after updating to version 4.4.0

### ISSUE THREAD

**Issue by gtolarc** [isaachinman/next-i18next#699] opened 2020-05-04 07:08 UTC
After updating to version 4.4.0, multiple cookies were created as follows. Can you see why?

Middleware has been changed to i18next-http-middleware, but I use fastify, not express. Could this be the cause?

At least version 4.3.0 had no problems with fastify.

![스크린샷 2020-05-04 오후 4 03 46](https://user-images.githubusercontent.com/8623798/80943123-6b17ac80-8e21-11ea-93b8-fd4969f852e2.png)

**Comment by condorman** [comment] 2020-05-04 07:45
same problem, i follow the simple tuttorial in src code.

**Comment by isaachinman** [comment] 2020-05-04 09:11
This seems to be reproducible on next-i18next.com.

@adrai We seem to have a critical error in the new i18next deps. Release is [here](https://github.com/isaachinman/next-i18next/releases/tag/v4.4.0).

**Comment by adrai** [comment] 2020-05-04 09:35
I'm investigating....

**Comment by isaachinman** [comment] 2020-05-04 09:43
Thanks - I don't have a lot of time this morning but let me know if I can help in any way. Not sure if this is an implementation issue, but we didn't have this issue with the previous i18next packages. The [example](https://github.com/isaachinman/next-i18next/tree/master/examples/simple) is what runs on the domain above and should be able to repro.

**Comment by adrai** [comment] 2020-05-04 10:01
@isaachinman should be fixed with i18next-http-middleware@1.0.2

**Comment by isaachinman** [comment] 2020-05-04 11:29
@adrai Is there test coverage for this bug?

**Comment by adrai** [comment] 2020-05-04 11:33
yes ;-)

**Comment by isaachinman** [comment] 2020-05-04 12:40
Great. Can you deprecate any/all broken versions of `i18next-http-middleware` via npm? I'm going to update `next-i18next` now.

**Comment by adrai** [comment] 2020-05-04 12:42
I generally don’t like to do this, because it’s only a bug for those who use the cookie caching option...
But if you really prefer, I will rethink about it.

**Comment by isaachinman** [comment] 2020-05-04 12:44
Fair point. Just wanted to prevent `next-i18next` users from unknowingly installing the broken versions. I can also just pin the dep within `next-i18next`. Let me know what you prefer - both approaches are fine for me.

**Comment by adrai** [comment] 2020-05-04 12:53
I would prefer you to update your package.json
`"i18next-http-middleware": "^1.0.2"`
or 
`"i18next-http-middleware": ">=1.0.2"`

**Comment by isaachinman** [comment] 2020-05-04 12:54
Sure, we can pin within `next-i18next`. Just want to point out that your first example there, `^1.0.2` would not result in the right versions being installed in all cases.

**Comment by adrai** [comment] 2020-05-04 12:58
you're right... let's do both ;-)

**Closed** 2020-05-04 12:58 UTC

**Comment by isaachinman** [comment] 2020-05-04 13:14
Released in v4.4.1.

**Comment by gtolarc** [comment] 2020-05-04 14:39
Although the number was reduced as follows, it still seems to have problems.
And I'm using a server-side cookie library called nookies, and the part of setting the cookie on the server side is broken in my case.

![스크린샷 2020-05-04 오후 11 35 50](https://user-images.githubusercontent.com/8623798/80977999-7211df80-8e60-11ea-8b60-b5b0806d0358.png)

**Comment by adrai** [comment] 2020-05-04 14:47
@gtolarc I can’t reproduce this 🤷‍♂️

**Comment by gtolarc** [comment] 2020-05-04 15:02
After clearing the cookie completely and trying a few more times, it seems that the creation of multiple cookies has been fixed.
However, the server-side cookie setting was definitely broken. What is the reason? Here is a simple pseudo code.
```
import nookies from 'nookies';

IndexPage.getInitialProps = async (ctx) => {
  const cookies = nookies.get(ctx);
  if (!cookies.graphicsQuality) {
    nookies.set(ctx, 'graphicsQuality', 'high', { maxAge: 2592000 }); // <- doesn't work..
  }
  return { namespacesRequired: ['common'] };
};
```

**Comment by isaachinman** [comment] 2020-05-04 15:06
@gtolarc That's got nothing to do with `i18next` or `next-i18next`. Please post elsewhere. Good luck!

**Comment by gtolarc** [comment] 2020-05-05 02:08
But, commenting this out and running it will make the server side cookie work. Is it really not related to i18next-http-middleware? @isaachinman @adrai 

https://github.com/isaachinman/next-i18next/blob/bdd48e3caf5dd83e8e990b05d1d2ce8a6651b975/src/middlewares/next-i18next-middleware.ts#L44

**Comment by adrai** [comment] 2020-05-05 06:38
@gtolarc can you investigate on which inner part of i18nextMiddleware would be related to this?
I can't reproduce this.

**Comment by isaachinman** [comment] 2020-05-05 07:27
@gtolarc If your issue is caused by using this `nookies` package, it has nothing to do with `i18next` or `next-i18next`. As far as I can tell it's as simple as that, but do let us know if you believe otherwise.

**Comment by gtolarc** [comment] 2020-05-05 09:57
I looked at the i18next-http-middleware code, so I think following part is the problem. It should be a way to keep and add, not overwrite the set-cookie.

https://github.com/i18next/i18next-http-middleware/blob/cf5c9a29391d54aebc83c840b9ea3a3cce73232c/lib/languageLookups/cookie.js#L87

In the existing i18next-express-middleware, it is.
https://github.com/i18next/i18next-express-middleware/blob/master/src/languageLookups/cookie.js#L42

**Comment by adrai** [comment] 2020-05-05 11:14
@gtolarc can you try with i18next-http-middleware@1.0.4 ?

**Comment by gtolarc** [comment] 2020-05-05 11:24
oh, it works! @adrai thank you guys.

**Comment by adrai** [comment] 2020-05-05 11:31
@gtolarc thanks to you...
Are your set-cookie headers looking ok now?

**Comment by gtolarc** [comment] 2020-05-05 12:13
sure

**Comment by isaachinman** [comment] 2020-05-05 13:09
Ah, @gtolarc I understand now. Thanks for helping us figure that one out!
