### ISSUE TITLE
Keep getting: "You have not declared a namespacesRequired array on your page-level component: undefined"

### ISSUE THREAD

**Issue by bgold0** [isaachinman/next-i18next#79] opened 2019-01-05 06:15 UTC
> You have not declared a namespacesRequired array on your page-level component: undefined. This will cause all namespaces to be sent down to the client, possibly negatively impacting the performance of your app. For more info, see: https://github.com/isaachinman/next-i18next#4-declaring-namespace-dependencies

I keep getting the following error but I feel like I have `namespacesRequired` on all my page level components.

Can someone help figure out where this is actually talking about so I can get to the bottom of it?

**Comment by isaachinman** [comment] 2019-01-05 10:53
If you provide a reproducible example (repo), I can help debug. Thanks!

**Comment by bgold0** [comment] 2019-01-05 15:33
@isaachinman I appreciate that. Is there a simple way to debug myself? Doing some sort of console to to figure out what file it is talking about or something of that nature?

My repo is quite big so it'll take me some time.

**Comment by isaachinman** [comment] 2019-01-06 11:18
We'd need to track down the component itself, not the URL. It looks like in your case the URL is just a hot update because you're in dev mode. Perhaps console log the entire component class and see what it is? It might be the NextJs error page.

**Comment by cr05s19xx** [comment] 2019-01-09 14:01
@isaachinman  I placed a `console.log` (I know, not a good idea 😅) inside `node_modules/next-i18next/dist/hocs/app-translation.js Line 178`

```javascript
console.log(pageProps);
consoleMessage('warn', "You have not declared a namespacesRequired array on your page-level component: ".concat(Component.displayName, ". This will cause all namespaces to be sent down to the client, possibly negatively impacting the performance of your app. For more info, see: https://github.com/isaachinman/next-i18next#4-declaring-namespace-dependencies"));
```

I received the output `{ "statusCode": 404 }`, which leads me to believe this error is being thrown by the `_error.js` page (which in my case has not been created yet).

Could this be the cause? If so, can you suggest a remedy?

**Comment by isaachinman** [comment] 2019-01-09 14:10
Can you please provide a reproducible example (repo)?

**Comment by isaachinman** [comment] 2019-01-09 14:34
Do you mean that sending `requiredNamespaces` instead of `namespacesRequired` caused you to see the console warning of `You have not declared a namespacesRequired array... undefined`? It sounds like the error you're describing is exactly the purpose of the warning in the first place.

**Comment by cr05s19xx** [comment] 2019-01-09 14:58
@isaachinman Exactly. My point is that I spoke too soon 😅

**Comment by bgold0** [comment] 2019-01-09 14:59
Yea I don't believe he's having the same issue as me. I will need some time getting something reproducible. I will attempt to console log the entire component and see what I get. I appreciate the fast response @isaachinman

**Comment by isaachinman** [comment] 2019-01-09 15:02
No problem, just let me know.

**Comment by VBagmut** [comment] 2019-01-10 12:33
In my case I solved problem by renaming js files in locales folder to json.

**Comment by laxplaer** [comment] 2019-01-10 14:52
I solved this issue by providing `favicon.ico`, which was adding 404 error and causing this warning.

**Comment by isaachinman** [comment] 2019-01-10 20:06
Yeah, I suspect `displayName` for the Next error page(s) is `undefined`, but need a good way to reproduce this. A normal 404 will probably do the trick - will take a look as soon as I have availability.

**Comment by isaachinman** [comment] 2019-01-10 20:46
Should be fixed with 34e8e08. Released with v0.18.0.

**Closed by isaachinman** 2019-01-10 20:46 UTC

**Comment by isaachinman** [comment] 2019-01-10 20:53
Huh... it just occurred to me that while `undefined` is not helpful, this error _might actually be a good thing_ and we maybe shouldn't be excluding it as 34e8e08 does. Most likely people are going to want to manually declare their own `_error.js` page and specifically localise it.

I've opened an issue in the NextJs repo to track this:

https://github.com/zeit/next.js/issues/6026

Hopefully we can get that fixed on the NextJs and then revert 34e8e08.

**Comment by therealchewbecca** [comment] 2019-07-09 22:31
> I solved this issue by providing `favicon.ico`, which was adding 404 error and causing this warning.

@laxplaer Thanks for the fix!

**Comment by irvv17** [comment] 2020-10-15 05:01
> I solved this issue by providing `favicon.ico`, which was adding 404 error and causing this warning.

So, this is not about next-i18n__?

**Comment by Alexander2317** [comment] 2020-10-17 06:54
@isaachinman I have the same warning with next.js@9.5.5.
If I create 404.js page and _error.js I see this warning.
If I remove 404.js I see a warning from next.js
`Warning: You have added a custom /_error page without a custom /404 page. This prevents the 404 page from being auto statically optimized.
See here for info: https://err.sh/next.js/custom-error-no-custom-404
`
How to fix it?)

**Comment by fabioriva** [comment] 2020-10-22 07:11
@isaachinman Same as Alexander2317

**Comment by michaelmorgantalabat** [comment] 2020-10-23 19:41
I tried to use `getStaticProps` with `404.tsx` and still same issue as @Alexander2317 

import { I18nPage } from 'lib/i18n';
import { GetStaticProps } from 'next';

const ErrorPage: I18nPage = () => <h1>404</h1>;

export const getStaticProps: GetStaticProps = async () => {
  return {
    props: {
      namespacesRequired: ['common'],
    },
  };
};

export default ErrorPage;
`
`

**Comment by Alexander2317** [comment] 2020-10-24 08:30
My ``_error.jsx``

```
// @flow

import * as React from 'react'
import Head from 'next/head'

import { withTranslation } from '../i18n'
import { Layout } from '../components'

import style from './_error.module.css'

type Props = {
  statusCode?: any,
  t: Function,
}

const Error = ({ statusCode, t }: Props): React.Node => {
  const message = statusCode
    ? t('error-with-status', { statusCode })
    : t('error-without-status')
  return (
    <>
      <Head>
        <title>{message}</title>
      </Head>
      <Layout>
        <p style={style.title}>{message}</p>
      </Layout>
    </>
  )
}

Error.getInitialProps = async ({ res, err }) => {
  let statusCode = null
  if (res) {
    ;({ statusCode } = res)
  } else if (err) {
    ;({ statusCode } = err)
  }
  return {
    statusCode,
    namespacesRequired: ['common', 'header', 'footer'],
  }
}

Error.defaultProps = {
  statusCode: null,
}

export default (withTranslation('common')(
  Error,
): React.AbstractComponent<Props>)

```

And `404.jsx`

```
// @flow

import * as React from 'react'
import Head from 'next/head'

import { constants } from '../__data__'
import { withTranslation } from '../i18n'
import { Layout, Link } from '../components'

import style from './404.module.css'

type Props = {
  t: Function,
}

const Custom404 = ({ t }: Props): React.Node => (
  <>
    <Head>
      <title>{t('error-404-status')}</title>
    </Head>
    <Layout>
      <h1 className={style.title}>{t('error-404-status')}</h1>
      <Link route={constants.routes.base}>{t('error-404-link')}</Link>
    </Layout>
  </>
)

export default (withTranslation(['common', 'header', 'footer'])(
  Custom404,
): React.AbstractComponent<Props>)

```

I tried to use `getInitialProps` in `404.jsx`, `getStaticProps` but it didn't solve the problem because then we'll see the following error
`Error: page /404 getStaticProps can not be attached to a page's component and must be exported from the page. See more info here: https://err.sh/next.js/gssp-component-member`
