### ISSUE TITLE
Adding/updating a translation in the file doesn't update until `yarn dev`  is run again

### ISSUE THREAD

**Issue by ZahidSaeed7** [isaachinman/next-i18next#1264] opened 2021-06-17 22:02 UTC
## Describe the bug
I recently added this library to my NextJS project. I followed the example mentioned on this page:
https://github.com/isaachinman/next-i18next/blob/master/examples/simple/pages/index.js

The problem is, whenever I add/update an existing translations file, the changes do NOT take effect in the development environment. If I add/remove new values to the `props` field in the `getStaticProps` and refresh the page, those external properties are affected/updated but the translations always remain the same as when we run the `yarn dev`.

## Occurs in next-i18next version
I'm using version 8.5.0

## Expected behavior
The translations should be updated without re-running the `yarn dev` every single time.

**Comment by isaachinman** [comment] 2021-06-18 08:08
Duplicate of #108 #214 #881 #796.

**Closed by isaachinman** 2021-06-18 08:08 UTC

**Comment by ZahidSaeed7** [comment] 2021-06-18 11:04
@isaachinman Thank you for responding. I've checked the previous issues. I'm not having a custom server. How can I make it to work in such a case then?

**Comment by addamove** [comment] 2021-06-21 12:44
Same...

**Comment by isaachinman** [comment] 2021-06-21 12:55
Something like:

```
nodemon --watch public/locales --exec "yarn dev"
```

**Comment by tbsvttr** [comment] 2021-11-23 12:52
This should be build in functionality in development mode.

**Comment by kachkaev** [comment] 2021-12-27 14:13
[next-remote-watch](https://github.com/hashicorp/next-remote-watch) can help here, but yeah – it’d be cool if this was a built-in feature 🙂
