### ISSUE TITLE
SSG Support

### ISSUE THREAD

**Issue by underfisk** [isaachinman/next-i18next#872] opened 2020-11-02 14:31 UTC
## Is your feature request related to a problem? Please describe.
I'm trying to use next18-i18next in a nextjs SSG app, the issue is that it throws constantly warnings in pages that doesn't need translations, other times it only allow loading the translations by receiving through props TFunction and doesn't allow me to use the hook (useTranslation). I set namespacesRequired at getInitialProps and it ignores, even if I use getStaticProps it does

## Describe the solution you'd like
I'm not sure if there is any workaround to use with SSG but it would be amazing to

## Describe alternatives you've considered
I think that getStaticProps is not being considered but it should in order to support SSG

**Comment by isaachinman** [comment] 2020-11-02 14:34
Duplicate of #869.

**Closed by isaachinman** 2020-11-02 14:34 UTC
