### ISSUE TITLE
Warnings loading locales/Multiple not loading

### ISSUE THREAD

**Issue by underfisk** [isaachinman/next-i18next#873] opened 2020-11-02 15:04 UTC
## Describe the bug
I receive a lot of warnings even though I declared namespacesRequired and also if I declare multiple namespaces, It only loads the first

## Occurs in next-i18next version
next-i18next v: 7.0.1
npm v: 6.14.5
node v: 12.16.1

## Steps to reproduce
Create an empty SSG app, export normally as in the documentation and try as in the screenshots provided

## Expected behaviour
Load all the namespaces required and avoid having so much warnings

## Screenshots
![t1](https://user-images.githubusercontent.com/15980884/97883165-6b372d00-1d1c-11eb-8907-9eddd1dbaaf1.png)
![t2](https://user-images.githubusercontent.com/15980884/97883177-6d00f080-1d1c-11eb-906e-85441e12903a.png)
![t3](https://user-images.githubusercontent.com/15980884/97883180-6e321d80-1d1c-11eb-98c0-3d35176ede3d.png)
![t4](https://user-images.githubusercontent.com/15980884/97883183-6ecab400-1d1c-11eb-9069-3016aaf89f7a.png)

## OS (please complete the following information)
 - Device: Laptop
 - Browser: All

**Comment by isaachinman** [comment] 2020-11-03 11:17
This package does not yet support `getStaticProps`, as we have an SSR runtime requirement. Please read through previous issues.

I will also loosely consider this another duplicate of #869.

**Closed by isaachinman** 2020-11-03 11:17 UTC

**Comment by underfisk** [comment] 2020-11-03 12:18
@isaachinman But even with SSR ON, i get a lot of warnings as I said before in pages like 404 and if I have multiple locales it does not load. I had to force my deployment to be SSR instead of SSG and the problem persists, its not about SSG anymore, seems an issue to me

**Comment by isaachinman** [comment] 2020-11-03 14:34
Not sure I understand your problem/question. At the present moment, you need to use `getInitialProps` with this package.

**Comment by underfisk** [comment] 2020-11-03 14:36
I did use getInitialProps, the issue is that pages like 404 can't have the translation otherwise it throws error. Also as I said, even with getInitialProps multiple locales are not loaded (I'm at next v10) and it just keeps throwing warnings.
Randomly i get "renderer more hooks than previously" with this plugin context, I can gather a screenshot of the stack and you'll eventually see that something is not right

**Comment by isaachinman** [comment] 2020-11-03 14:38
If you can put together a simple reproducible repo showing these errors, I'd be happy to take a look. Thanks!

**Comment by underfisk** [comment] 2020-11-03 14:39
Okay i'll sure do it
