### ISSUE TITLE
Setting `localeSubpaths` to foreign language dict doesn't work

### ISSUE THREAD

**Issue by hgezim** [isaachinman/next-i18next#494] opened 2019-09-05 20:32 UTC
## Describe the bug
Setting `localeSubpaths` to a dict that doesn't include `en:'en'` (my default language), causes 404s when url with locale path is requested. E.g. '/de', '/cs'.

## Occurs in next-i18next version
1.1.2

## Steps to reproduce
You must provide a reproducible repository, or copy/paste blocks of code which are sufficient to reproduce the bug.

```
import NextI18Next from 'next-i18next'


const localeSubpathVariations = {
  none: {},
  foreign: {
    cs: 'cs',
    de: 'de'
  },
  all: {
    de: 'de',
    en: 'en',
    cs: 'cs',
  },
}

const NextI18NextInstance = new NextI18Next({
  defaultLanguage: 'en',
  otherLanguages: ['cs', 'de'],
  localeSubpaths: localeSubpathVariations['foreign'],
  logging: true,
  fallbackLng: 'en'
} as any)

export default NextI18NextInstance;

export const {
    appWithTranslation,
    withTranslation,
    Link
  } = NextI18NextInstance
```

This is what I see when I do that:

```
$ curl -I http://commerceowl.haproxy
HTTP/1.1 200 OK

$ curl -I http://commerceowl.haproxy/de
HTTP/1.1 404 Not Found

$ curl -I http://commerceowl.haproxy/cs
HTTP/1.1 404 Not Found
```

However, if I change `localeSubpaths` to include all the languages `localeSubpaths: localeSubpathVariations['all'],`, I no longer get 404s:

```
$ curl -I http://commerceowl.haproxy
HTTP/1.1 302 Found
Location: /en

$ curl -I http://commerceowl.haproxy/de
HTTP/1.1 200 OK

$ curl -I http://commerceowl.haproxy/cs
HTTP/1.1 200 OK
```

## Expected behaviour
I expect when I set `localeSubpathVariations` to only foreign languages, I can access my site in default language without using a path and when I use a path (e.g. `/de`), it should load the site localized with German, for example.

## Screenshots
If applicable, add screenshots or a GIF to help explain your problem.

## OS (please complete the following information)
 - Device: Mac (27-inch, Late 2012)
 - Browser: curl, Firefox 68.0.2 (64-bit) 

## Additional context

When foreign is set for `localSubpathVariations` and I pass an `Accept-Language` header with a value, I get some strange results:

```
$ curl -H 'Accept-Language: en' -i http://commerceowl.haproxy
# Status 200 and proper English translation 
$ curl -H 'Accept-Language: cs' -I http://commerceowl.haproxy/cs
# Status 200 and proper Czech translation
```

The above seems fine, but this makes little sense:
```
$ curl -H 'Accept-Language: en' -i http://commerceowl.haproxy/cs
# Status 404
$ curl -H 'Accept-Language: en' -i http://commerceowl.haproxy/de
# Status 404
$ curl -H 'Accept-Language: cs' -i http://commerceowl.haproxy/de
# Status 200 and proper German translation!!!! That's unexpected... since I'm passing Accept-Language of `cs` for Czech and since when I pass `en` I get a 404.
```

**Comment by isaachinman** [comment] 2019-09-05 20:37
Duplicate of #469.

**Closed by isaachinman** 2019-09-05 20:37 UTC
