### ISSUE TITLE
Fetch a namespace from another server / cdn

### ISSUE THREAD

**Issue by aralroca** [isaachinman/next-i18next#262] opened 2019-04-09 17:25 UTC
I'm not sure if it is possible to do it with the current configuration, however I don't found it.

**Problem**

Currently, I have all my locales inside the `/static/locales` folder. Nevertheless, I want now to load another namespace, but this time from another server, and just this namespace.

How can I do it? Is there a way? If not, would be nice to implement it 🙂

**Comment by kachkaev** [comment] 2019-04-09 17:37
Thanks an interesting suggestion. Another thing to explore is network caching of namespace files. At the moment, every time I switch from `page1` to `page2`, a real request to `/static/locales/page2.json` is made. What would be cool is if the URLs for namespace files had some kind of hash and were cached by the browser forever (`/static/locales/page2.asdfasdfdsf.json` or `/static/locales/page2.json?h=asdfsdafs`). When the contents of the source json (or yaml) changes, the URL changes so browser cache is missed and a real request is sent to the server.

**Comment by isaachinman** [comment] 2019-04-09 17:41
Duplicate of #163.

**Closed by isaachinman** 2019-04-09 17:41 UTC
