### ISSUE TITLE
 Problem with GetServerSideProps and ServerSideTranslations

### ISSUE THREAD

**Issue by KevinArangu** [isaachinman/next-i18next#1575] opened 2021-12-07 17:39 UTC
I am using getServerSideProps instead of getStaticProps on my page. When using it in a dev server it works, but when I deploy in Vercel that page gives me 500: internal server error.

Versions:
i18nexus-cli: "^2.0.2"
next: "12.0.3"
next-i18next: "^10.0.1"
react: "17.0.2"

THIS CODE WORKS IN MY PROJECT

![Captura de pantalla 2021-12-07 133115](https://user-images.githubusercontent.com/38361709/145077892-8c29bd8a-6c84-4726-8a23-938ff3f914de.png)

THIS CODE NOT WORK

![Captura de pantalla 2021-12-07 133308](https://user-images.githubusercontent.com/38361709/145079132-842287ca-2d3c-4594-a776-63785f73b95d.png)

NOTE: I need to use getServerSideProps because I have dynamic routes (/example/[id])

Here my "next-i18next.config":

![Captura de pantalla 2021-12-07 133617](https://user-images.githubusercontent.com/38361709/145078689-7cd94dbd-3737-4b3e-a987-b1bef63a0910.png)

Any recommendation or configuration to be able to use getServerSideProps? Thanks.

**Comment by isaachinman** [comment] 2021-12-07 17:48
Duplicate of #1552, and many others before it.

**Closed by isaachinman** 2021-12-07 17:48 UTC

**Comment by KevinArangu** [comment] 2021-12-07 19:15
Thanks for help. It worked for me!
