### ISSUE TITLE
Can't use it in 404 page, Is there a way to do it ?

### ISSUE THREAD

**Issue by its-mXc** [isaachinman/next-i18next#1304] opened 2021-07-07 10:42 UTC
Hi, i have run into a small issue in  custom 404 page, as i can't use get server side props. Is there a alternate solution ?

PS: Thanks for the package

**Comment by isaachinman** [comment] 2021-07-07 10:58
Duplicate of #1058, #1235.

**Closed by isaachinman** 2021-07-07 10:58 UTC
