### ISSUE TITLE
Language selected in client is not being used on next server re-render

### ISSUE THREAD

**Issue by sudhirt4** [isaachinman/next-i18next#120] opened 2019-01-22 14:54 UTC
After changing the client side language using ``i18next.changeLanguage``method (or directly manipulating the ``i18next`` cookie value) and then refreshing the page the language selected is not being used by the SSR.

This used to work before, Facing this issue after upgrading from ``0.16.0`` to ``0.20.0``

**Comment by isaachinman** [comment] 2019-01-22 18:14
@capellini Any idea where this regression could be located? I assume it's within `app-with-translation`. Also, we'll need an e2e test to cover this once a bug fix is in place to prevent future regression.

**Comment by isaachinman** [comment] 2019-01-22 18:16
@sudhirt4 Very sorry for the trouble here, please bear with us while we debug this - it has the highest priority at the moment.

**Comment by isaachinman** [comment] 2019-01-22 18:18
@sudhirt4 Update - I cannot reproduce this via the [example](https://github.com/isaachinman/next-i18next/tree/master/example). If I load into an incognito window (served English), change the language to German on the client side, and do a hard reload, I get served an SSR page in German.

Please provide a reproducible repo/example for us to debug. It's either a bug in more complex use cases, or user error.

**Comment by isaachinman** [comment] 2019-01-22 18:19
Are you using the `i18n` instance that `next-i18next` exports to change the language, [as seen here](https://github.com/isaachinman/next-i18next/blob/master/example/pages/index.js#L18)?

**Comment by capellini** [comment] 2019-01-22 21:03
> I cannot reproduce this

@isaachinman - neither can I.  Both `changeLanguage` and changing the cookie work for me.

> we'll need an e2e test to cover this once a bug fix is in place to prevent future regression.

:+1: agreed

@sudhirt4 Would you mind installing v0.17, v0.18, and v0.19 and tell me what specific major version causes the code to break?

**Comment by ngocketit** [comment] 2019-01-22 22:02
I got the same problem. Calling `i18n.changeLanguage()` on client updates the `i18next` cookie to the correct langcode but then it's switched back with the default value when the page is refreshed.

**Comment by ngocketit** [comment] 2019-01-22 22:22
But I couldn't reproduce with the example either, weird!

**Comment by ngocketit** [comment] 2019-01-22 22:57
Alright, I can confirm that it works when NODE_ENV is set to production but not with development. Any ideas?

**Comment by capellini** [comment] 2019-01-22 23:13
I just came across one scenario (still looking for more) where this could happen with [this change](https://github.com/isaachinman/next-i18next/commit/e7ae318a6df47d2d8592ca61d9b140cf36bf60c2#diff-629eb664116efd2a55d4c6361f00c9bd) in `lngPathDetector`.

Scenario assumes:
1. `localeSubpaths` is enabled
2. Language that is currently selected is not the default language
3. User switches to another non-default language
4. Current URL is refreshed in the browser

Scenario:
Assume language is currently 'zh', default language is 'en' and possible languages are ['en', 'zh', 'de'] and we are currently on page '/zh/page':
1. Change the language to 'de'
2. Refresh the browser -- URL = '/zh/page' and language from the cookie is 'de'
3. Since `req.url.startsWith('/zh/')` and `language !== 'zh'`, invoke `i18n.changeLanguage(zh)`

In the old code:
1. Code continues on to next `if` statement, since `language !== 'en'` and `!req.url.startsWith('/de/')`, redirect to `/de/page` and everything works as expected.

In the new code:
1. Set `languageChanged = true`
2. The `if` statement above never gets executed, and we remain at `/zh/page` with language changed to `zh`.

**Comment by capellini** [comment] 2019-01-22 23:19
@ngocketit If you don't mind, could you please help me narrow down which specific version caused the bug?
```bash
npm i next-i18next@0.17

# is the bug still there?

npm i next-i18next@0.18

# is the bug still there?

npm i next-i18next@0.19

# is the bug still there?
```
I know that's a hassle and I apologize for the inconvenience, but it would help us identify where to look more quickly.

**Comment by sudhirt4** [comment] 2019-01-23 00:49
@capellini : I just confirmed it stopped working when changed from ``0.16`` to ``0.17``

**Comment by sudhirt4** [comment] 2019-01-23 00:55
As I mentioned in this PR (Ref: GH-121), the problem seem to be the current language not being returned [here](https://github.com/isaachinman/next-i18next/blob/master/src/hocs/app-with-translation.js#L46) . The changes in that PR fixed the issue for me, let me know if it is relevant or I can make some changes there.

**Comment by sudhirt4** [comment] 2019-01-23 01:30
After setting values for "otherLanguages" on my config it seems to work on my application as well.

**Comment by capellini** [comment] 2019-01-23 02:33
> Was able to recreate this on example setting otherLanguages to default values.

Yes, but this happened with default values, even with v0.16, right?  In other words, even with v0.16, if you change language in the cookie to the default language and then navigate to '/[locale]/page', it still changes the locale to [locale].

> After setting values for "otherLanguages" on my config it seems to work on my application as well.

Even in [the case mentioned above](https://github.com/isaachinman/next-i18next/issues/120#issuecomment-456600125)?

> the problem seem to be the current language not being returned [here](https://github.com/isaachinman/next-i18next/blob/master/src/hocs/app-with-translation.js#L46)

I see.  Let me look into that.  Thanks.

**Comment by sudhirt4** [comment] 2019-01-23 03:54
> Yes, but this happened with default values, even with v0.16, right? In other words, even with v0.16, if you change language in the cookie to the default language and then navigate to '/[locale]/page', it still changes the locale to [locale].

I am not using `localeSubpaths` so cannot confirm that. In my case it used to work without defining `otherLanguages` in `0.16`

**Comment by capellini** [comment] 2019-01-23 04:08
@sudhirt4 I see.  Thanks.

@isaachinman This issue stems from 50bf6c8.  The reason why it worked in version v0.16 is because [we were only using `req.i18n.languages[0]`](https://github.com/isaachinman/next-i18next/blob/5f8450b0ceb44991897e91b1cb150a4b2129852a/src/utils/lng-path-detector.js#L3) to initialize `language`, whereas with that change, we then required `allLanguages` to include the language.  However, since @sudhirt4 was using `whitelist` instead of `otherLanguages`, the whitelisted languages are not included in `allLanguages`.

This explains why [this PR](https://github.com/isaachinman/next-i18next/pull/121) appeared to solve the problem.  Since `(l) => req.i18n.language || allLanguages.includes(l)` evaluates to true always, it was always returning `req.i18n.languages[0]`, restoring the same functionality before 50bf6c8 and giving the appearance of fixing things.

Though `whitelist` is a [valid `i18next` configuration option](https://www.i18next.com/overview/configuration-options), it is [not a valid `next-i18next` option](https://github.com/isaachinman/next-i18next#options).

**Comment by ngocketit** [comment] 2019-01-23 11:43
Yes I could also confirm that it's somehow related to `otherLanguages` setting. Without it, it won't work. The `NODE_ENV` value that I mentioned above is just a coincidence.

**Comment by sudhirt4** [comment] 2019-01-23 13:50
I guess the confusing thing about this is the meaning of `otherLanguages`. Like in my case I was using the `whitelist` property to define the same behaviour.

If it is a required field then it must be mentioned in docs.

**Comment by capellini** [comment] 2019-01-23 13:57
The only action I can see from this issue is to perhaps make it a little more clear in the docs.

We should also probably revise the comment at the bottom of the options table too ("This table contains options which are specific to next-i18next. All other i18next options can be passed in as well.").  In this case, it seems as though the `defaultLanguage` and `otherLanguages` `next-i18next` options supplant the `i18next` `whitelist` option?

**Comment by isaachinman** [comment] 2019-01-23 14:42
I would like to see:

1. Docs updated to indicate which options are required
2. Error (not warning) thrown during initialisation if a required option is not provided

**Comment by isaachinman** [comment] 2019-01-23 14:43
@sudhirt4 Sorry for the lack of clarity on our part. I hope your issue has been resolved now, though?

**Comment by capellini** [comment] 2019-01-23 15:21
@isaachinman - What do you think about adding a "Specifying Languages" section to the documentation?  `otherLanguages` is not strictly necessary (of course, in reality you want to specify some, otherwise why use any i18n package in the first place) and the default is reasonable.  I think it just needs to be a little more explicit that `whitelist` should not be used.

Also, would it be good for us to populate `whilelist` in `src/config/create-config.js` if it isn't already specified?

**Closed** 2019-01-23 17:14 UTC
