### ISSUE TITLE
React 18, next 12 experimental::concurrentFeatures does not work with this library

### ISSUE THREAD

**Issue by PupoSDC** [isaachinman/next-i18next#1568] opened 2021-12-06 22:36 UTC
## Describe the bug

When activating concurrent mode from Reat 18 a functioning app will throw this error:

```
wait  - compiling /_error (client and server)...
wait  - compiling...
error - Error: Cannot find module for page: /
error - ./node_modules/next-i18next/dist/commonjs/serverSideTranslations.js
Module not found: Can't resolve 'fs' in '/home/ppuposad/dev/wood-for-you/node_modules/next-i18next/dist/commonjs'
Native Node.js APIs are not supported in the Edge Runtime with `concurrentFeatures` enabled. Found `fs` imported.
```
which usually happens when one runs `serverSideTranslations` in client code. 

## Occurs in next-i18next version

`10.0.1`
## Steps to reproduce

activate concurrent mode: https://nextjs.org/docs/advanced-features/react-18
add translations to index page:

```
export const getServerSideProps: GetServerSideProps = async ({
  locale = "pt",
}) => {
  return {
    props: {
      ...(await serverSideTranslations(locale, ["common", "homePage"])),
    },
  };
};
```
App will crash with the experiemntal flag. It will work without it.

## Expected behaviour

App should work

## OS (please complete the following information)

- Ubuntu 21.10
- Chromium 96.0.4664.45 snap

## Additional context

This is somewhere between a bug / feature request since it relates to a beta feature. 
It may also be a bug on next side, but I thought I would start the discussion here.

**Comment by isaachinman** [comment] 2021-12-07 09:18
Duplicate of #1533.

**Closed by isaachinman** 2021-12-07 09:18 UTC
