### ISSUE TITLE
/enhello-world is matched as /hello-world

### ISSUE THREAD

**Issue by felixmosh** [isaachinman/next-i18next#500] opened 2019-09-09 11:46 UTC
## Describe the bug
I have a page `/hello-world` and a config
```
{
  browserLanguageDetection: false,
  serverLanguageDetection: false,
  defaultLanguage: 'he',
  otherLanguages: ['en'],
  localeSubpaths: {
    en: 'en',
  },
}
```
Whenever I navigate to `/enhello-world` is matched as `/hello-world`

## Occurs in next-i18next version
v1.2.0

## Steps to reproduce
see above

## Expected behaviour
it should not clean that url because it is starts with lang.

## OS (please complete the following information)
 - Device: [e.g. MBP 2018 13"]
 - Browser: [e.g. Chrome 70.0.3538.77]

## Additional context
From my debugging, looks like [this regex](https://github.com/isaachinman/next-i18next/blob/master/src/middlewares/next-i18next-middleware.ts#L22) should have a slash after the langs.

**Comment by felixmosh** [comment] 2019-09-09 12:11
If I change the path in the link to `/:subpath(${Object.values(localeSubpaths).join('|')})/(.*)` this will not catch root path with second lang, such as: `domain.com/en`.

BTW, why `domain.com/en` is not mapped to `domain.com/en/` (with a slash at the end)?

**Comment by isaachinman** [comment] 2019-09-09 16:22
@felixmosh I cannot reproduce this. Please provide a repository.

**Comment by felixmosh** [comment] 2019-09-09 20:25
I've reproduced it here:
https://codesandbox.io/s/next-i18next-issue500-id6bw

navigate to https://id6bw.sse.codesandbox.io/deabout, it will render to `about` page in `de`

**Comment by isaachinman** [comment] 2019-09-09 20:33
That's not what I'm seeing:

![Screen Shot 2019-09-09 at 21 33 08](https://user-images.githubusercontent.com/10575782/64564448-77f30780-d349-11e9-8868-03ee90d32695.png)

**Comment by felixmosh** [comment] 2019-09-10 05:08
What do you mean, the middle were removes the prefix of de, and pass about page to next, even though it is wrong and none existing url....

Thing of a page with a name `desserts`, will be handled as `sserts` if you have support in de language

**Comment by isaachinman** [comment] 2019-09-10 07:00
Ah, I understand your point. I think [this line](https://github.com/isaachinman/next-i18next/blob/master/src/middlewares/next-i18next-middleware.ts#L86) is going to be the root of it.

Feel free to contribute!

**Comment by felixmosh** [comment] 2019-09-10 08:13
Cool, I will review a way to fix that.
I'm thinking that the root cause it the fact that [this](https://github.com/isaachinman/next-i18next/blob/master/src/middlewares/next-i18next-middleware.ts#L83) if is returning a match even though it shouldn't.

As I mentioned [here](https://github.com/isaachinman/next-i18next/issues/500#issuecomment-529443130), I think that it is better to enforce a slash **after**  the language part.
1. WDYT about this?
2. There is an edge case that `/de` (as a de path of root [`/`]) will not cached as such, then do you think that we should enforce a trailing slash in that case?

**Comment by isaachinman** [comment] 2019-09-10 08:14
I removed trailing slash enforcement and won't be adding it back. That's an easy way to fix the problem, but not the correct way.

**Comment by felixmosh** [comment] 2019-09-10 09:12
I'm not sure that you have answered my questions.

Is this lib had a slash enforcement after the lang prefix?

**Comment by isaachinman** [comment] 2019-09-10 12:16
Sorry!

Yes, you are right that the `params` variable is return something other than false in those cases. However, I think that entire code block needs to be wrapped in an `if` for `currentLngSubpathIsPresent`. We only need to modify `req.url` if we are currently on a subpath. The rest of the functionality is just fine - no redirect is occurring.

This package used to enforce trailing slashes across all routes, and now does not enforce them anywhere. Trailing slashes are up to the end user and are way too opinionated for a package like this.

**Comment by felixmosh** [comment] 2019-09-10 13:53
Cool, will look at the values of that variable at the later today. thanx.

**Comment by felixmosh** [comment] 2019-09-10 18:48
Tell me, why [those functions](https://github.com/isaachinman/next-i18next/blob/master/__tests__/middlewares/next-i18next-middleware.test.ts#L20-L29) were mocked?

**Comment by felixmosh** [comment] 2019-09-10 19:34
I've removed all the implementation mocks, and looks like It found another bug...
![image](https://user-images.githubusercontent.com/9304194/64644357-2f0b8380-d41b-11e9-886a-e72b310b4e14.png)

**Comment by isaachinman** [comment] 2019-09-11 10:08
Hi @felixmosh. The file you're referring to is a unit test for the middleware. The utils are mocked because they have their own unit tests. Indeed, there's probably room for improvement, but testing overall functionality is better left to something like [supertest](https://www.npmjs.com/package/supertest).

I do not understand what that image means, but if you believe you've found a bug please open an issue for it.

**Comment by felixmosh** [comment] 2019-09-11 10:10
Ok, can u review the changes that I've made in this PR.
It solves 2 issues, I can split it if needed

**Closed** 2019-09-12 07:33 UTC
