### ISSUE TITLE
Babel doesn't polyfill according preset-env

### ISSUE THREAD

**Issue by StarpTech** [isaachinman/next-i18next#290] opened 2019-05-02 13:32 UTC
## Describe the bug
As mentioned in https://github.com/isaachinman/next-i18next/issues/107 I expected that es6 functions are polyfilled but it's not. If you check the `dist/es/utils/lng-path-corrector` there is no polyfill for `Array.includes`. This throws in IE Edge.

**Comment by isaachinman** [comment] 2019-05-02 13:35
We transpile to the same target that NextJs does. Polyfilling is up to the user. Am I misunderstanding?

**Comment by StarpTech** [comment] 2019-05-02 13:39
mmh.. babel doesn't transpile `ǹode_modules` by default. Any idea how I can solve it with current nextjs version? I tried the `with-polyfill` example but it doesnt work.

**Comment by isaachinman** [comment] 2019-05-02 13:44
Transpiling and polyfilling are two separate concerns. See https://github.com/zeit/next.js/issues/4572#issuecomment-395960145.

Ideally we'd like to support all browsers that NextJs does out of the box as well.

Does this throw in IE11? If so, we can think about improving that.

**Comment by StarpTech** [comment] 2019-05-02 13:52
Yeah, I already read it but it doesn't my answer how to polyfill a third party lib with a regular next setup. From my understanding next-i18next should provide a compatible version for all browsers because it's not part of the next babel process right?

**Comment by isaachinman** [comment] 2019-05-02 13:56
> a compatible version for all browsers 

No, absolutely not. We aim to support the same subset of browsers that NextJs does.

**Comment by StarpTech** [comment] 2019-05-02 13:58
Sry, I mean all browsers that NextJs that includes ie11+.

**Comment by isaachinman** [comment] 2019-05-02 13:59
If `next-i18next` breaks in IE11, please provide a detailed report and we'll fix it.

**Comment by StarpTech** [comment] 2019-05-02 15:34
I could fix it by adding the 

```js
import 'core-js/es6/array';
import 'core-js/es7/array';
```
to the polyfills.js as shown in the `with-polyfill` example. We should add it to the readme.

**Comment by kachkaev** [comment] 2019-05-02 16:12
Related: https://github.com/isaachinman/next-i18next/issues/107

IMO this lib does not have to support IE11 out of box but for any steps enabling that, a section in README would be helpful.

**Comment by StarpTech** [comment] 2019-05-02 16:57
I'm corious how it works if you import these as functions `/fn/... . From my understanding in that way it can't work because the prototype isn't touched.

**Comment by StarpTech** [comment] 2019-05-02 17:02
@isaachinman at the end the module will fail due to exact such missing methods. This means next-i18n doesn't support the same browsers as nextjs. I'm fine with documenting it in the Readme. I will send a PR.

**Comment by isaachinman** [comment] 2019-05-02 17:48
As I've stated, I'd very much like for this package to support the exact same browsers that NextJs does, because this package is an enhancement _on top of_ NextJs.

**Comment by abelsoares** [comment] 2019-06-03 10:25
I think you guys really need to figure this out, otherwise, this module becomes a little useless.

**Comment by isaachinman** [comment] 2019-06-03 10:28
Hi @abelsoares, welcome. This is open source software and is developed in the free time of contributors. Feel free to contribute yourself.

**Comment by aralroca** [comment] 2019-06-28 08:10
I have a similar problem in IE11 with arrow functions. Looks that they are not transpiled by babel...

![image](https://user-images.githubusercontent.com/13313058/60327730-efd9a480-998c-11e9-80dd-663511da28f5.png)

**Comment by isaachinman** [comment] 2019-06-28 08:13
@aralroca Which target are you consuming, `commonjs` or `es`?

**Comment by aralroca** [comment] 2019-06-28 08:32
@isaachinman I have an independent file with all the things of i18n (including NextI18Next instance) with commonjs, because also my custom server with node v11 is consuming the instance with:

```js
const { i18n } = require('../i18n')
// ...
server.use(nextI18NextMiddleware(i18n))
```
Do you think this should be fixed changing node 11 to node 12 (that I see that support es modules): http://2ality.com/2019/04/nodejs-esm-impl.html and replacing common.js to es modules everywhere?

Thanks!

**Comment by isaachinman** [comment] 2019-06-28 08:35
I think you misunderstood my question. This package, `next-i18next`, transpiles to two separate targets.

Upgrading Node is not going to do anything for your browser support. You'll need to do one of these things:

1. Transpile your `node_modules`
2. Use runtime polyfills
3. Submit a PR on this repo's `babelrc`

**Comment by aralroca** [comment] 2019-06-28 08:49
@isaachinman I know that the problem is not with the Node version itself, however, I'm using a shared file between server and browser in common.js with:

```js
const NextI18Next = require('next-i18next').default

//...

const i18n = new NextI18Next({
  customDetectors: [langFromDomain],
  defaultLanguage: DEFAULT_LOCALE,
  localeSubpaths: 'all',
  otherLanguages: LOCALES,
  pluralSeparator: '_',
  simplifyPluralSuffix: true,
  loadPath: `${BASE_URL_STATICS}/static/locales/{{lng}}/{{ns}}.json`,
  detection: {
    order: ['querystring', 'cookie', 'from-domain', 'navigator'],
  },
})
```

So the browser also is using the `require('next-i18next').default` instead of `import`. Can be this the problem?

**Comment by aralroca** [comment] 2019-06-28 21:17
@isaachinman I finally fixed transpiling only the `next-i18next` library with this in my `next.config.js` file:

```js
const withTM = require('next-transpile-modules')

// ...

module.exports = withTM({
  transpileModules: ['next-i18next'],
  ...nextConfig,
})
```

Thank you for your time! Was a big help :)

**Comment by isaachinman** [comment] 2019-06-28 22:38
@aralroca Which target are you importing? Our `cjs` target [is also `next/babel`](https://github.com/isaachinman/next-i18next/blob/master/.babelrc#L19).

**Comment by aralroca** [comment] 2019-07-08 13:33
@isaachinman as target are you refering to this?

```json 
"browserslist": [
    "last 2 versions",
    "> 1%"
  ]
```

**Comment by isaachinman** [comment] 2019-07-08 13:44
Yes, that's what I'm referring to. `next-i18next` transpiles to the same target that NextJs transpiles to. That said, there may be language features like `Object.values` which need to be polyfilled or transpiled themselves.

**Comment by isaachinman** [comment] 2019-07-16 19:05
I've now put the simple example online via Heroku and have updated the README. I've allocated a domain and the live demo can be found at [next-i18next.com](http://next-i18next.com/).

We can use this domain to do browser testing, etc, going forward.

**Comment by isaachinman** [comment] 2019-07-18 07:54
BrowserStack has been kind enough to support the project and I've had a chance to test this in IE11. Should be fully supported with #402.

**Closed** 2019-07-18 14:01 UTC
