### ISSUE TITLE
_app is unmounted when changing query params

### ISSUE THREAD

**Issue by alexpuertasr** [isaachinman/next-i18next#1638] opened 2022-01-20 14:07 UTC
## Describe the bug

The appWithTranslation HOC in some way is unmounting the _app when the user navigate with queries.
I updated a simple example to show it: 

[Example](https://github.com/alexpuertasr/next-i18next-issue)

## Steps to reproduce
The user should start from a query route like /second?query=test in my example (in the first loading will unmount once already), and if the use tries to navigate to other pages the app will be unmounted again.

## Expected behaviour
The _app should never be unmounted to persist data

## Screenshots

First I'm loading /second that works as spected an after I refresh on /second?query=test and app start to be unmounted:

![next-i18next-bug](https://user-images.githubusercontent.com/10731590/150353400-feed5878-5566-4af8-8e7c-2a7a72b63964.gif)

**Comment by isaachinman** [comment] 2022-01-20 14:12
@alexpuertasr Can you check if this is a duplicate of #1628?

**Comment by alexpuertasr** [comment] 2022-01-20 14:38
@isaachinman I tried adding the memo wrapping appWithTranslation(MyApp) and seems to solve the issue, I don't know if the origin of the problem will be the same one but looks like.

**Comment by isaachinman** [comment] 2022-01-20 14:55
Yep, sounds like the same issue. We're very close to merging a fix 👍

**Closed by isaachinman** 2022-01-20 14:55 UTC
