### ISSUE TITLE
localeSubpaths generate TypeError in force-trailing-slash.js

### ISSUE THREAD

**Issue by ldbglobe** [isaachinman/next-i18next#69] opened 2018-12-24 10:43 UTC
I just try to run the source example with localeSubpaths  set to true

Here is my i18n.js (only change made)

```
const NextI18Next = require('next-i18next')

module.exports = new NextI18Next({
	otherLanguages: ['de'],
	localeSubpaths: true
})
```

And then, each page load result in lots of warning in the shell

```
TypeError: Cannot read property 'options' of undefined
    at _default (...\node_modules\next-i18next\dist\utils\force-trailing-slash.js:15:12)
```

--- (the full trace is too long and not really usefull) ---

Page generation still work and translation are in place, but kinda worry about all those warnings about a missing i18n object 

https://github.com/isaachinman/next-i18next/blob/master/src/utils/force-trailing-slash.js (line 5)

```
req.i18n.options.allLanguages.forEach((lng) => {
```

**Comment by isaachinman** [comment] 2018-12-24 11:07
Ah, this is related to #68. Those errors are presumably throwing on non-next requests, because `req.i18n` in indeed now undefined due to [this](https://github.com/isaachinman/next-i18next/blob/master/src/middlewares/next-i18next-middleware.js#L11) recent addition.

**Comment by ldbglobe** [comment] 2018-12-24 11:08
Additionnal problem => lot's of assets loads returing header 500 on each page load

![image](https://user-images.githubusercontent.com/1027535/50397993-85913e80-0774-11e9-8ec1-49bf2a20a4bb.png)

**Comment by isaachinman** [comment] 2018-12-24 11:08
That's not an additional problem, that's the same problem. Fix coming shortly.

**Comment by ldbglobe** [comment] 2018-12-24 11:10
Enjoy your work ! and your reaction time
Thk's

**Comment by isaachinman** [comment] 2018-12-24 11:11
@capellini It'd be good for us to somehow test execution of some clientside JavaScript to ensure that the example isn't broken like this. Any interest in setting up e2e/smoke testing?

@ldbglobe No problem, thank you for your patience. This project is still young and I'm still working out some kinks.

**Comment by isaachinman** [comment] 2018-12-24 11:16
Fixed and released in v0.14.3.

**Closed by isaachinman** 2018-12-24 11:16 UTC

**Comment by isaachinman** [comment] 2018-12-24 12:35
@ldbglobe Can you let me know if the issue is resolved on your end?

**Comment by capellini** [comment] 2018-12-24 15:58
> Any interest in setting up e2e/smoke testing?

@isaachinman - sure thing...do you have any preferred packages?

**Comment by ldbglobe** [comment] 2018-12-24 16:01
No more issue 👌

My project build without localeSubpaths at first work just fine now with the option activated.

Thanks a lot for your amazing plugin !

**Comment by isaachinman** [comment] 2019-01-03 14:12
Basic e2e testing added with 08b0449.
