### ISSUE TITLE
Type error: Type 'null' is not assignable to type 'UserConfig'.

### ISSUE THREAD

**Issue by ghoshnirmalya** [isaachinman/next-i18next#997] opened 2021-02-26 10:58 UTC
## Describe the bug
**yarn build** is throwing **Type error: Type 'null' is not assignable to type 'UserConfig'.**

## Occurs in next-i18next version
8.0.2

## Steps to reproduce
**Contents of next-i18next.config.js:**
```ts
module.exports = {
  i18n: {
    defaultLocale: 'en',
    locales: ['en'],
  },
};
```

**Contents of next.config.js:**
```ts
const { i18n } = require('./next-i18next.config');

module.exports = {
  i18n,
};
```

**Contents of pages/_app.tsx:**
```ts
import { wrapper } from '@core/redux/store';
import type { AppProps } from 'next/app';
import React from 'react';
import { appWithTranslation } from 'next-i18next';

const App = ({ Component, pageProps }: AppProps) => {
  return <Component {...pageProps} />;
};

export default appWithTranslation(wrapper.withRedux(App));
```

**Contens of pages/index.tsx:**
```ts
import Locale from '@custom-types/locale';
import { NextPage } from 'next';
import { useTranslation } from 'next-i18next';
import { serverSideTranslations } from 'next-i18next/serverSideTranslations';
import React from 'react';

type IProps = {
  hello: string;
};

const IndexPage: NextPage<IProps> = ({ hello }) => {
  const { t } = useTranslation('common');

  return (
    <div>
      <h1>{t('h1')}</h1>
      {hello}
    </div>
  );
};

export async function getServerSideProps({ locale }: Locale) {
  return {
    props: {
      hello: 'world',
      ...(await serverSideTranslations(locale, ['common', 'footer'])),
    },
  };
}

export default IndexPage;
```

## Expected behaviour
**yarn build** should build the Next.js project without throwing any errors.

## Screenshots
<img width="834" alt="Screenshot 2021-02-26 at 4 21 59 PM" src="https://user-images.githubusercontent.com/6391763/109291751-5c3a3480-784f-11eb-9c27-9e9c307bd691.png">

## OS (please complete the following information)
 - Device: MacBook Air 2019, macOS BigSur
 - Browser: Chrome 88.0.4324.192

**Comment by alexjamesmacpherson** [comment] 2021-02-26 11:42
This issue probably has a similar root cause to #995

**Comment by bbigras** [comment] 2021-02-26 18:05
> This issue probably has a similar root cause to #995

Yeah, probably. I don't have the problem if I use 8.0.1.

**Comment by isaachinman** [comment] 2021-02-26 18:51
I'm going to close this in favour of #995. I have created a repo there and would love if someone can assist in helping me repro these issues. Thanks!

**Closed by isaachinman** 2021-02-26 18:51 UTC
