### ISSUE TITLE
Typescript serverSideTranslations argument type error

### ISSUE THREAD

**Issue by jeromeycg** [isaachinman/next-i18next#1330] opened 2021-07-23 02:29 UTC
The initialLocale argument of serverSideTranslations not accepting undefined while the locale from getStaticProps context could be.

```typescript
export const getStaticProps: GetStaticProps = async function({ locale }: GetStaticPropsContext) {
  return {
    props: {
      ...(await serverSideTranslations(locale, ["common", "footer"]))
    }
  };
};
```

<img width="531" alt="擷取" src="https://user-images.githubusercontent.com/85729168/126730881-675d63ee-cd20-4d65-bfeb-e5b4587ded5d.PNG">

**Comment by isaachinman** [comment] 2021-07-23 08:56
Duplicate of #1307.

**Closed by isaachinman** 2021-07-23 08:56 UTC
