### ISSUE TITLE
Using Link with localeSubpaths not working correctly with dynamic routes

### ISSUE THREAD

**Issue by AhmadAlYaaqba** [isaachinman/next-i18next#731] opened 2020-06-04 13:38 UTC
## Describe the bug
when using localeSubpaths and then try to import using Link from **next-i18next** instance for _dynamic route_, it will **not** work, for ex

`<Link href="/[dynamicComponent]" as="/test">`

i will get the following error on console: 

`
Uncaught (in promise) Error: The provided "as" value (/en/test) is incompatible with the "href" value (/[dynamicComponent]). Read more: https://err.sh/vercel/next.js/incompatible-href-as
`

## Occurs in next-i18next version
`"next-i18next": "^4.4.2"`

## Steps to reproduce
same as the describe of the bug

## Expected behaviour
Expected to route me to the correct dynamic routes without issue and add the lang in URL.

## OS (please complete the following information)
 - Device: MBP 2015
 - Browser: Chrome 83.0.4103.61

**Comment by isaachinman** [comment] 2020-06-04 13:42
Duplicate of #413.

**Closed by isaachinman** 2020-06-04 13:42 UTC
