### ISSUE TITLE
Question: Do you have support/any way of localizing next routes ?

### ISSUE THREAD

**Issue by kristijorgji** [isaachinman/next-i18next#1416] opened 2021-09-09 15:30 UTC
I am using default next localization, and works fine for basic things like having a structure `pages/login.tsx` then
defining in next.config.js two locales, will work fine like below:

/en-US/login
/de-DE/login

I would like to have exact functionality working, but have custom subpath mapped to a locale, so for example

/en/login -> and in code for locale in getStatic|ServerProps context to get locale en-US
/de/anmelden -> map to use `pages/login.tsx` again, and in code get de-DE

next-i18next.config.js
```
const path = require('path');

module.exports = {
    localePath: path.resolve('./public/static/locales'),
    i18n: {
        defaultLocale: 'en_US',
        locales: ['en_US', 'de_DE'],
    },
};

```

next.config.js

```
const { i18n } = require('./next-i18next.config');

/** @type {import('next/dist/server/config').NextConfig} */
module.exports = {
    i18n,
    async rewrites() {
        return [
// partially works, is broken next client thinks still is en-US language redirect is not working correctly
            {
                source: '/de/anmelden',
                destination: '/de_DE/login',
            },
        ];
    },
};

```

**Comment by isaachinman** [comment] 2021-09-09 15:36
Duplicate of #1381 (where I have provided one possible answer).

**Closed by isaachinman** 2021-09-09 15:36 UTC

**Comment by kristijorgji** [comment] 2021-09-09 15:41
Thanks, yes it is a duplicate almost, but given solution is not relevant. They get the paths from a database(cms), and we know exactly the paths like simple ones login register just want them localized for different lcoles

**Comment by isaachinman** [comment] 2021-09-09 15:44
The fact that many users use a CMS is irrelevant. You can hardcode the paths if you like, store them in JSON, etc.

**Comment by kristijorgji** [comment] 2021-09-09 15:54
It is partially relevant, because login register and other pages have their own react components /pages/login.tsx register.tsx and so on, while all cms posts are somewhere at /pages/posts/[slug].tsx so is fine they are handled by same component.

This is a very bad messy solution for normal pages , having something like pages/[whateverurl].tsx then inside it how can we differentiate if it is the login page or register or contact ? and return different views (which is not supported by next also).

If next would support returning "views" in getserversideprops, then such ugly solution would work okish,

if (cmsEntry.urlKey === 'login') {
return {
props: someprops,
page: 'pages/login'
}
}
// and so on for the other pages register contact etc having different page handler

**Comment by isaachinman** [comment] 2021-09-09 15:55
I do agree with you wholeheartedly, but unfortunately this is a limitation of NextJs itself, and is not specific to internationalisation.

**Comment by kristijorgji** [comment] 2021-09-09 15:56
Sure, just gave it a try asked here maybe something available was out there. Thanks for the replies, if I came up somehow with some cleaner solution will share in next repo

**Comment by isaachinman** [comment] 2021-09-09 16:00
No problem. I do believe the `rewrites` and `getStaticPaths` are the two best options available.

For what it's worth, while translating the slugs of marketing pages may definitely be worthwhile, I wouldn't worry about translating URLs for pages like `login`, etc.

Feel free to have a look around at Fortune 100 websites, and see what they do – this is what the Vercel team did when constructing their i18n offering.
