### ISSUE TITLE
Usage of i18nextBrowserLanguageDetector should be optional

### ISSUE THREAD

**Issue by kachkaev** [isaachinman/next-i18next#32] opened 2018-12-06 09:16 UTC
I've been analyzing app bundle size and noticed that `i18next-browser-languagedetector` in the client bundle (2KB gz). Some projects may not to want this language detector, so it'd be great if it could be made an opt-in (i.e. required by the app's `i18n.js` rather than in `next-i18next`). See https://github.com/isaachinman/next-i18next/issues/16#issuecomment-444397728 for my example of an app that uses other language detectors.

**Comment by isaachinman** [comment] 2018-12-06 12:18
As far as I know, this project simply won't work without `i18next-browser-languagedetector`.

If you think that is not the case, please set up a PR demonstrating how it might function without it.

**Comment by kachkaev** [comment] 2018-12-06 12:36
Following https://github.com/zeit/next.js/pull/5761, this project is advertised as a complete replacement of a custom `react-i18next` integration into Next.js. This suggests that users should not expect to experience any regressions and will be able to port what they've already had into the new abstraction.

If that's the case, I'm happy to help with thinking about how to achieve this. However, if `next-i18next` positions itself as an opinionated integration with a certain set of features rather than a generic one, please let us know – we won't need to overcomplicate it 😉

**Comment by isaachinman** [comment] 2018-12-06 12:41
By nature it is opinionated. We're using NextJs, Express, and so on.

I want to stress to you that achieving translation in a SSR app is _not easy_. It took me several weeks of deep diving to get to the current point this project is at, and I am confident when I say that this is the best solution currently available, and requires significant inside knowledge.

I do not know what you mean when you say "regression". This project _is_ a complete replacement for whatever custom implementations people might have, but that doesn't mean it's going to be zero kb or have no deps.

If you can figure out how to extract `i18next-browser-languagedetector` from the project in a sensible way, I would of course accept that PR.

**Comment by jamuhl** [comment] 2018-12-06 12:41
That PR more states it replaces the current sample provided - as that sample was causing to much troubles - with users having no experience in next.js nor i18next and throwing in additional complexity using redux, ... and expecting things magically to work without the need to program and understand the different parts.

So my opinion next-i18next is the way to go for new users - but in certain points it needs to be opinionated - either you got zero-configuration (= hidden hardcoded configuration) or a solution having all options but not working out of the box...which would mean we're at the same point...not sure if there is something in between

**Comment by isaachinman** [comment] 2018-12-06 12:43
Yes, @jamuhl's point is a good one.

@kachkaev If you find a way to remove `i18next-browser-languagedetector`, it will still be enabled by default, as it is the sensible choice.

**Comment by kachkaev** [comment] 2018-12-06 13:22
I totally see the point of making the life of new users easier and also like the idea of zero-config tools! Making something zero-config does not imply making more advanced use cases impossible to do – `create-react-app` or `next.js` itself are truly good example of that.

Removing `i18next-browser-languagedetector` seems possible if we introduce an _optional_ config parameter (e.g. `disableBrowserLanguageDetector: boolean`), which would block calls to `.use(i18nextMiddleware.LanguageDetector)` and `.use(i18nextBrowserLanguageDetector)` in [create-i18next-client.js](https://github.com/isaachinman/next-i18next/blob/master/src/create-i18next-client.js). However, in this case, `i18next-browser-languagedetector` will still be in the client bundle (+2KB gz).

Alternatively, we could go for a slightly more verbose `i18n.js`:

```diff
 const NextI18Next = require('next-i18next').default
+const i18nextBrowserLanguageDetector = require('i18next-browser-languagedetector').default

-module.exports = new NextI18Next({ otherLanguages: ['de'] })
+module.exports = new NextI18Next({ otherLanguages: ['de'], use: [i18nextBrowserLanguageDetector] });
```

This will not change things for a newcomer – they copy-paste this stuff anyway. Frankly speaking, `next-i18next` is not zero-config because of this file and `server.js`; it would be if we just needed to `yarn add next-i18next`.

As of the usefulness of not having `i18nextBrowserLanguageDetector`, I can easily give you a simple example: my min-website 🙂. https://en.kachkaev.ru/ is _always_ in English and https://kachkaev.ru/ is _always_ in Russian (regardless of `?lng=xyz`, cookies, etc.). Other folks might want to have such website mirrors with a toggle in a top-right corner to switch the language (that would take users to another website). The benefit of this approach is that search engines index the content in the same language it will be later viewed. No magic like _The article was in English in search results and it's in German when I open it_.

**Comment by isaachinman** [comment] 2018-12-06 18:06
How do you plan to support your subdomain with this package, though?

I can tell you straight away that we will not be forcing users to install `i18next-browser-languagedetector` separately and worry about that. I do appreciate your careful inspection of the work here, and it's now clear that we need an easy and effective pattern to allow users to opt in to certain transpiled areas.

Doing evals inside `if` statements feels dirty (because it is), but it's the simplest way I can think of.

Any other ideas? @jamuhl?

**Comment by jamuhl** [comment] 2018-12-06 18:11
Personally, i would focus on the main case and leave all customization to userland...looking at the number of questions already placed here adding more options will only make people more struggle...users which like to something very different can still take this as inspiration - but having one source solving it all - looking at how long we already work on react-i18next + next i not believe in that anylonger...to much wanted, too complex

**Comment by kachkaev** [comment] 2018-12-06 22:47
Perhaps, `i18next-browser-languagedetector` can be declared in `next-i18next` dependencies, just not included into the bundle unless a user is requiring it in `i18n.js` as I suggested above (that’s just copy-pasting).

If `i18nextBrowserLanguageDetector` is mentioned in the `use` option, it becomes apparent that this particular detector can be replaced with something else. If so, less confusion and fewer open issues.

I’m not sure I can agree with @jamuhl this time, although I can imagine how overwhelmed he can be by getting all those different requests in the main libraries. The theoretical surface area of this module is much smaller, which means that it _can_ be a one-size-fits-all thing. My belief is that the module is almost there, it just needs a couple of things to be reshuffled a bit. No harm will be made to the newcomers’ experience. There are quite a few other next plugins that are both easy to start with and can be also customized in tens of ways. Quite a nice source for inspiration!

**Comment by kachkaev** [comment] 2018-12-06 22:49
> How do you plan to support your subdomain with this package, though?

I’m already doing this in a local experimental branch where I’m adding a couple of server-side language detectors. I can share it over the weekend when I get some extra time.

**Comment by kachkaev** [comment] 2018-12-09 10:09
Here is the source code of an example website that uses `i18next` with no browser-based langauge detector: https://gitlab.com/kachkaev/website-frontend. I switched it to `next-i18next@0.8.0` yesterday and [told webpack](https://gitlab.com/kachkaev/website-frontend/blob/88911497aec89f3c797d499ba26424d798e2f02d/src/next.config.js#L26-33) to not include server-side modules into the client to minimize bundle size (this is a pretty dirty workaround for https://github.com/isaachinman/next-i18next/issues/33).

What would be cool is to be able to configure server-side language detectors in `server.ts`, so that `i18n.ts` did not have to import private website config ([example](https://gitlab.com/kachkaev/website-frontend/blob/327084969e1fa5d1a8d3c13fb7bd1ee02468014c/src/config.ts)). Here is how I'd like my code to look like: https://gitlab.com/kachkaev/website-frontend/commit/958d96352778bf96f34460af90ea26ac2f930cd3
* ICU plugin is mentioned in `i18n.ts`, because it's used on the client and on the server.
* Server-side language detectors sit in `server.ts` and so don't spill over to the client.
* No reference to `config.ts` in `i18n.ts`.
* No need to define i18n-related modules as [webpack externals](https://webpack.js.org/configuration/externals/) to avoid large client bundle size.
* No `i18next-browser-languagedetector` logic if the project does not use it.

For these changes to happen, I need to be able to pass a modifier to the i18n config in `server.ts` (see fourth parameter in `nextI18NextMiddleware()`. This means that `i18n` should not be initialized by then. Can it be initialized lazily? E.g. when calling `nextI18NextMiddleware` or `appWithTranslation` 🤔

With these possible changes the API, a minimal example would look like this:

```js
// i18n.js
const NextI18Next = require('next-i18next').default
const i18nextBrowserLanguageDetector = require('i18next-browser-languagedetector').default

module.exports = new NextI18Next({ otherLanguages: ['de'], use: [i18nextBrowserLanguageDetector] });
```

```js
// server.js
const i18nextMiddleware = require('i18next-express-middleware')
const express = require('express')
const next = require('next')
const nextI18NextMiddleware = require('next-i18next/middleware')

const nextI18next = require('./i18n')

const app = next({ dev: process.env.NODE_ENV !== 'production' })
const handle = app.getRequestHandler();

(async () => {
  await app.prepare()
  const server = express()

  nextI18NextMiddleware(nextI18next, app, server, config => {
    config.use = [i18nextMiddleware.LanguageDetector]
  })

  server.get('*', (req, res) => handle(req, res))

  await server.listen(3000)
  console.log('> Ready on http://localhost:3000')
})()
```

The only breaking change for existing users is that they have to explicitly inject the language detector into `nextI18next`. For newcomers things look the same, because they just copy-paste two files.

**Comment by isaachinman** [comment] 2018-12-09 13:20
We've already discussed this request in [another issue](https://github.com/isaachinman/next-i18next/issues/33#issuecomment-444971804):

> This package will export an already-initialised i18n instance. That is non-negotiable and is a decision made from quite a lot of experience in this realm.

@kachkaev I believe your use case is far outside the normal use of this package, so of course you're going to run into issues. For certain advanced use cases, I will always recommend you hand roll your own solution. Feel free to use this package as inspiration, or ask me for help, but we're not going to be able to cover 100% of use cases.

I have come around though, and do think that use of `i18next-browser-languagedetector` should be optional. I have added a new config option called `browserLanguageDetection` with 1b629bc. It's `true` by default, but you can disable it, and `i18next-browser-languagedetector` will be omitted from your bundle, saving about 6kb without gzip.

Please note that you're probably going to want to remove `header` from your `detection` settings to achieve what you want, because your server itself is still checking the browser lang.

This will most likely be released with `v0.9.0`.

**Closed by isaachinman** 2018-12-09 13:20 UTC

**Comment by kachkaev** [comment] 2018-12-09 13:56
I'm not sure that adding `config.browserLanguageDetection` and doing `eval("require('i18next-browser-languagedetector')")` on the browser side is a working solution – webpack does not know how to resolve `eval`. So the only option to exclude `i18next-browser-languagedetector` is not to mention it in any `next-i18next` code and let the users import it in their `i18n.js`.

I also can't agree that a website that defines the language purely on the server and not based on the user's browser / cookie is a rare case. Take Wikipedia, for example. Any other website that wants _all_ language mirrors to be available at their own URLs and thus be indexed by search engines will fall into the same category (https://www.apple.com/, https://www.apple.com/ru/). Having _one_ collection of URLs that toggle a language based on the users' preferences is more of a case of a web app rather than a website.

As of the _already-initialised i18n instance_, I agree with you that `i18n` needs to be always initialized in the eyes of a user. To be precise, your module does not return an initialized `i18n` even now, this happens only when I call `new NextI18next()`, i.e. `i18n` does not come initialized out of box. Given `i18n.js` exports a bunch of things, what matters is that `i18n` should be initialized _any time any of those things are used_. The details don't matter. This is why I am suggesting that `nextI18NextMiddleware` and `appWithTranslation` can call `i18n.init()`, not `new NextI18next()`. The users don't care about such change, but this trick makes it possible to inject some extra config into `i18n` inside `server.js`.

> I will always recommend you hand roll your own solution.

This is what I've been doing for about a year now. However, as I've said above, I believe that it _is_ possible to come up with a universal solution, just like this happened with [css](https://www.npmjs.com/package/@zeit/next-css) and [typescript](https://www.npmjs.com/package/@zeit/next-typescript) in Next.js. It's fine if you don't agree here, but I see this as a lost opportunity for your library to become _the one_ for everyone who uses Next.js and next-i18next.

**Comment by kachkaev** [comment] 2018-12-09 13:59
BTW: instead of `eval("require('something')")` you can use `eval('require')('something')` ([Prettier folks do that](https://github.com/prettier/prettier/blob/cdcb7b11c9afc850ab24420407144772983eefee/src/main/parser.js#L47)). This saves you from nested brackets and makes syntax highlighting a bit better.

**Comment by isaachinman** [comment] 2018-12-09 14:00
> I'm not sure that [...] is a working solution

I believe it is. Please inform me if it's not. I tested in prod mode and noticed a reduction of 6kb.

> I also can't agree that a website that defines the language purely on the server and not based on the user's browser / cookie is a rare case.

Doesn't matter - it's possible with `next-i18next` now.

> I see this as a lost opportunity

What exactly is lost? I implemented the exact functionality that this issue requested.

**Comment by kachkaev** [comment] 2018-12-09 14:14
> What exactly is lost?

It is still impossible to add language detectors in `server.js`, because by the time `nextI18NextMiddleware()` is called, `i18n` is already initialized. As a result, the only choice is to put _server-only_ language detectors into `i18n`, which adds their logic to the browser bundle and unnecessary exposes it to the users. It's not only about a few extra bits in the bundle, but also about the intellectual property that potentially gets leaked. Generally speaking, putting server-side logic into `i18n.js` is a pretty shaky path and it's very easy to do this wrong (it took me a few hours yesterday to play around webpack's external module config and make things right).


> I tested in prod mode and noticed a reduction of 6kb.

The reduction of the bundle size is explainable. But does language detection work when you enable `browserLanguageDetection`? If yes, this may be because `i18nextMiddleware.LanguageDetector` calculated the language on the server and told the client-side bundle to kick off with the value of `initialLanguage` in the store. Turns out that language detection on the _client_ does not add any value, because Next.js apps are rendered on the server first.

**Comment by kachkaev** [comment] 2018-12-09 14:33
Thinking about this a bit more, I'm getting more convinced that `i18next-browser-languagedetector` is not needed in Next.js apps and can only bring harm. Exactly as you say @isaachinman, if the client-side language value differs from the whatever server-side language detector has resolved and put into `initialLanguage`, the website will flash in one language and then switch to the other. I can't imagine a project when this is desirable, the only exception can be some modern art installation 😅

**Comment by kachkaev** [comment] 2018-12-09 14:35
This brings us back to to the idea of injecting language detectors in `server.js`, not `i18n.js` 🤔 But now this applies to language detectors of _any_ kind.

**Comment by isaachinman** [comment] 2018-12-09 19:55
> To be precise, your module does not return an initialized i18n even now, this happens only when new NextI18next() is called

That's a more or less irrelevant point, as you cannot use this module _at all_ without first initialising a new class. Class construction is just an implementation detail, and makes sharing context a bit easier. We could just as easily refactor the codebase to be entirely functional.

> This is why I am suggesting that nextI18NextMiddleware and appWithTranslation can call i18n.init(), not new NextI18next(). The users don't care about such change, but this trick makes it possible to inject some extra config into i18n inside server.js.

It seems like bad design to me intuitively.

More concretely, I think we'd run into problems wherein translations are not actually ready during SSR. The `init` function [takes a callback](https://github.com/i18next/i18next/blob/master/src/i18next.js#L31), but I'm not sure that the callback being called means that your desired translations are actually ready to go. Moreover, it might take several updates to fetch resources, resulting in several React tree renders, which is not possible during SSR. For this to work, we would need confirmation from @jamuhl that the init callback is only called after translations are ready.

> It's not only about a few extra bits in the bundle, but also about the intellectual property that potentially gets leaked.

To be absolutely clear, we're discussing language detectors which _modify the behaviour of a client side application_. The language selection logic is already opaque to your end users, and you're using OSS to achieve it. I'm all for IP protection but let's not confuse the matter here.

**To conclude:**

1. Unless `init` provides a dependable callback (or preferably promise) after which we can immediately render, none of this is possible.
2. If @jamuhl agrees that client side browser language detection makes no sense for SSR apps, we'll remove `i18next-browser-languagedetector` entirely. As it stands, it's already optional.

**Comment by isaachinman** [comment] 2018-12-09 21:32
@kachkaev Feel free to open an issue regarding this server side stuff and lazy initialisation. However, I need to think long and hard about if/how we can accomplish that. I don't want to derail an otherwise solid project just to support advanced use cases.

**Comment by kachkaev** [comment] 2018-12-09 22:08
> I'm not entirely sure what value they're getting out of this package

The benefit of any package named `next-***` is the same in all cases: it reduces the size of the boilerplate. Adding `nextI18NextMiddleware(...)` to `server.js` and `nextI18next.appWithTranslation(...)` to `_app.js` has reduced the number of lines for me dramatically, which is awesome! 🎉  From my previous experience, a Next plugin named `next-%SOMETHING%` usually tries to support all the flavours of _SOMETHING_ equally well (i.e. not limiting the use of _SOMETHING_ to a single _default_ scenario). This might be an incorrect conclusion based on my limited exposure to the ecosystem, but others might have the same expectations too when stumbling across `next-i18next` for the first time.

As of enabling or disabling `i18next-browser-languagedetector`, I still think that mentioning it explicitly inside the app's`./i18n.js` is more beneficial than having a config option that magically turns this functionality on and off. Configs are _implicit programming_, which makes the links between things looser compared to the explicit composition of things in the code. React, one of the most complex things we are all using, is able to work with zero config yet satisfies every user from a newcomer to an advanced one.

Not requiring `i18next-browser-languagedetector` inside the core `next-i18next` files is the only non-hacky way to exclude this library from the client-side bundle. IMO, this makes another case for changing the way it's picked.

**Comment by isaachinman** [comment] 2018-12-09 22:13
No plans to do that. The main purpose of this package is to support a fully SSR SPA out of the box, where language changes _can_ be fully SPA, including translation fetching and routing (no hard document requests ever). There is currently no other package that supports such a thing, anywhere (as far as I know). As @jamuhl mentioned, we can't support proper synchronisation between browser and server without the cookie support provided by `i18next-browser-languagedetector`.

**Comment by kachkaev** [comment] 2018-12-09 22:47
> The main purpose of this package is to support a fully SSR SPA out of the box

Totally with you here. What I'm suggesting by making the use of `i18next-browser-languagedetector` explicit in `i18n` to fix https://github.com/isaachinman/next-i18next/issues/16 and to allow for disabling cookies / uri params as means to alter the locale and free some space in the browser bundle. This is why I'm suggesting to change `i18n` the following way:

```js
const NextI18Next = require('next-i18next').default
const i18nextBrowserLanguageDetector = require('i18next-browser-languagedetector').default

module.exports = new NextI18Next({ otherLanguages: ['de'], use: [i18nextBrowserLanguageDetector] });
```

Same stuff as now, just an explicit `require` instead of a more implicit config option.


> we can't support proper synchronisation between browser and server without the cookie support

It seems that when locale subpaths are used, no cookie is needed (their clash would be contractionary). As of the behaviour of the `Link` exported from `i18n.js`, what it can be customized via composition? A good library design would allow a user of `next-i18next` to change between cookie approach (default) / subpaths / subdomains / custom domains by just changing how things are composed in `i18n.js` (and possibly `server.js` in addition). That would be quite cool!

**Comment by isaachinman** [comment] 2018-12-09 22:56
You're missing the point. `i18next-browser-languagedetector` is required for the default functionality of this package, so we're not going to remove it as a dep and have the majority of users reinstall it.

> It seems that when locale subpaths are used, no cookie is needed (their clash would be contractionary).

Yes, that's true. We also support projects which do not do any sort of route-to-locate mapping at all (the most basic of use cases).

> A good library design would allow a user of next-i18next to change between cookie approach (default) / subpaths / subdomains / custom domains by just changing how things are composed in i18n.js (and possibly server.js in addition).

Feel free to submit a PR. We've already discussed subdomains in #16.

**Comment by jamuhl** [comment] 2018-12-10 10:17
My point - most users do not care about the 8kb (or whatever https://bundlephobia.com/result?p=i18next-browser-languagedetector@2.2.4 -> 2kb gzipped nothing) the detector adds to the bundle - they are happy things work without having to dig deep into it.

What i miss: what is "common sense" - currently, this looks like replacing an opinionated solution with another opinionated solution - does it actually solve a "real" issue?

Example: You had an issue with `withNamespaces` -> which was a result of migration of an exiting project - would a new user of this module struggle with it? I guess no.

**Comment by isaachinman** [comment] 2018-12-10 15:39
@kachkaev You have argued your point passionately, and at length.

To be clear, I'm not worried about breaking changes whatsoever at this point.

Perhaps in the future we'll split `i18next-browser-languagedetector` out of the bundle to save 6kb, but it's not going to happen now. For now all deps will remain in a single package.

The main point is that the _functionality_ is now optional, and people can disable browser/header detection.

**Comment by isaachinman** [comment] 2018-12-10 15:42
> How open are you to the changes of this kind given the current size of the user base? If you consider the current API of the library as locked to serve existing 500 people, I'm afraid I cannot propose any solutions to the current issues. But if you are ready to re-consider some bits and make the components of the library more composable, I'm happy to get involved and help for the benefits of folks who want to integrate i18next into Next.

I am open to breaking changes and all suggestions.

**Please, keep issues limited to a SINGLE topic. If you have a new suggestion, open a new issue.**

**Comment by kachkaev** [comment] 2018-12-10 16:17
Before I open a new issue with the "functional" API proposal, are you happy with the following lines in `i18n.js`?

```js
import i18nextBrowserLanguageDetector from "i18next-browser-languagedetector";

export const nextI18next = new NextI18next({ otherLanguages: ['de'], use: [i18nextBrowserLanguageDetector] });
```
`i18next-browser-languagedetector` can be installed as a dependency to `next-i18next`, which will save newcomers from installing the second package. However, the presence of an explicit `import` that they'll blindly copy-paste will solve the bundle size problem right away.

**Comment by isaachinman** [comment] 2018-12-10 16:20
> For now all deps will remain in a single package.

Let's not go in circles any longer.
