### ISSUE TITLE
I don't want to use express, just next

### ISSUE THREAD

**Issue by EVALIJANI** [isaachinman/next-i18next#334] opened 2019-06-04 05:06 UTC
I don't want to use express, just next, is there a way to customize this for next only?

```
const {createServer} = require('http');
const {join} = require('path');
const {parse} = require('url');
const next = require('next');
const routes = require('./src/routes');

const port = parseInt(process.env.PORT, 10) || 4000;
const dev = process.env.NODE_ENV !== 'production';
const app = next({dev});
const handler = routes.getRequestHandler(app);

app.prepare()
    .then(() => {
        createServer((req, res) => {
            const parsedUrl = parse(req.url, true);
            const {pathname} = parsedUrl;

            if (pathname === '/service-worker.js') {
                const filePath = join(__dirname, '.next', pathname);
                app.serveStatic(req, res, filePath)
            } else {
                handler(req, res, parsedUrl)
            }
        }).listen(port, (err) => {
            if (err) throw err;
            console.log(`> Ready on http://localhost:${port}`)
        });
    });

```

**Comment by isaachinman** [comment] 2019-06-07 12:07
Duplicate of #274.

**Closed by isaachinman** 2019-06-07 12:07 UTC
