### ISSUE TITLE
Get 'language is not included' error on first time page request

### ISSUE THREAD

**Issue by vimutti77** [isaachinman/next-i18next#137] opened 2019-01-29 05:38 UTC
When I request page at first time. I get `Invalid configuration: Current language is not included in all languages array` in the browser console.

Also, If I remove `i18next` cookie and then refresh the page. The error message is occurred too.

This error message is only occurred when I enable `localeSubpaths`.

**Comment by isaachinman** [comment] 2019-01-29 10:13
@capellini I won't have time to look into this until this evening, but this could be related to the recent middleware changes as well. This was something I explicitly fixed in the past.

**Comment by capellini** [comment] 2019-01-29 14:50
@vimutti77 Could you please post your `i18n.js` file?

**Comment by vimutti77** [comment] 2019-01-29 15:03
This is my `i18n.js` file.
```
const NextI18Next = require('next-i18next')

const options = {
  localeSubpaths: true,
  otherLanguages: ['th'],
  localePath: 'public/locales',
}
module.exports = new NextI18Next(options)
```

After I did some test. I found that sometime the error occurred and sometime not.

**Comment by capellini** [comment] 2019-01-29 15:18
Thank you.  Also, what languages does your app support? 'en' and 'th'?

**Comment by capellini** [comment] 2019-01-29 16:52
I think this issue my be complicated by the fact that we're serving static files outside of the `static` directory, which Next expressly forbids, see this note in [the docs](https://github.com/zeit/next.js/#static-file-serving-eg-images):

> Note: Don't name the static directory anything else. The name is required and is the only directory that Next.js uses for serving static assets.

That said, in reality we often do need to serve static files outside of `static`. I was able to get our 'simple' example that used files outside of `static` working with the following configuration (and one bug fix):

__`server.js`__
```js
const express = require('express')
const next = require('next')
const nextI18NextMiddleware = require('next-i18next/middleware')

const nextI18next = require('./i18n')

const app = next({ dev: process.env.NODE_ENV !== 'production' })
const handle = app.getRequestHandler();

(async () => {
  await app.prepare()
  const server = express()

  server.use(nextI18NextMiddleware(nextI18next))

  // use '/public' for static files
  server.use('/public', express.static('public'))

  server.get('*', (req, res) => handle(req, res))

  await server.listen(3000)
  console.log('> Ready on http://localhost:3000') // eslint-disable-line no-console
})()
```

__`i18n.js`__
```js
const NextI18Next = require('next-i18next')

module.exports = new NextI18Next({
  ignoreRoutes: ['/_next', '/static', '/public'], // note that we have to redefine ignoreRoutes
  otherLanguages: ['de'],
  localeSubpaths: true,
  localePath: 'public/locales'
})
```

@vimutti77 The first thing that I would recommend is adding an `ignoreRoutes` key to your configuration like the one above.  Otherwise, we will try and process your static locale files.

@isaachinman There is a bug when the user defines their own `localePath`.  Sever-side we properly processes the change, but we don't client-side, resulting in a proper server-side render, but a 404 error when the user attempts to change locales client-side and retrieves locale files from the wrong location.  Though I was not able to get the same error as vimutti77, this is at least related to it.  PR forthcoming.

**Comment by isaachinman** [comment] 2019-01-29 18:00
@capellini I'm not sure we should be setting paths for users like you have done in #140. Isn't all of this definable by the user?

We definitely are not going to explicitly support serving locales out any dir except `static` - that's just a NextJs paradigm.

If users don't want to use a `static/locales` structure, they need to understand clearly what they are doing, and provide correct config options.

**Comment by capellini** [comment] 2019-01-29 18:33
> I'm not sure we should be setting paths for users like you have done in #140

Currently server-side [we already overwrite their paths here](https://github.com/isaachinman/next-i18next/blob/205d97da6a45591fdb6c746a070a8abb4d6e249f/src/config/create-config.js#L28-L31).  But client-side, they remain at their default or custom user-defined values.

Granted, in the current PR, I may need to guard and not change `config.backend` if the user has already defined their own paths, but in that case we should also guard the above-mentioned server-side code as well, right?

> We definitely are not going to explicitly support serving locales out any dir except `static` - that's just a NextJs paradigm.

Ok.

**Comment by isaachinman** [comment] 2019-01-29 19:49
Ah right, thanks for reminding me. I think my original idea was that it would be awfully nice if users only had to provide `localePath` and `localeStructure`, and have everything just work.

After seeing a few of these "my filesystem needs to be special" use cases, I'd rather put the entire burden on the user and not waste time on this sort of thing.

@capellini Do you think that's possible? I would like to fully support zero config for users who are willing to adopt a certain filesystem pattern, but shift all configuration onto users who do not want to. We can't support all these custom use cases.

**Comment by capellini** [comment] 2019-01-29 20:14
I like the way that you originally had it, with some adjustments.  I think it's reasonable to say that you can either have:
1. zero config
2. define `localePath` and `localeStructure` and zero config on `i18next-xhr-backend`; or
3. roll your own config in its entirety

Then again, you have seen far more use cases than I have.  Let me modify #140 to see if I can accommodate the three cases above.

**Comment by vimutti77** [comment] 2019-01-30 15:36
I try to reproduced the error by using the project from the simple example and then modify `i18n.js` file with this configs
```
const NextI18Next = require('next-i18next')

module.exports = new NextI18Next({
  localeSubpaths: true,
  otherLanguages: ['de'],
})
```

I test it by remove `i18next` cookie and then refresh the page about 8 times. And found that the error is occurred 3/8 times.

![ezgif-5-7b2c1609badb](https://user-images.githubusercontent.com/27840664/51992335-627a4d00-24df-11e9-97bd-0d2cadffa96d.gif)

**Comment by capellini** [comment] 2019-01-30 19:05
@vimutti77 I think I have a better handle on what's going on now.  I see that `en-US` is momentarily set as the language.  This happens within the `i18next-express-middleware` language detectors.  If the cookie is deleted (or otherwise not present), then the middleware checks the `accept-language` headers for what to set (and then, if no header can be found, it checks the query string).

@isaachinman Considering that we have no control over the client's `accept-language` headers, I think the best course of action is to ignore the language if it's not in the `allLanguages` array (I believe we did this before we decided to throw the error).  In other words, inside `lngPathCorrector`, just return` [as, query]` as though the default language is requested.

**Comment by capellini** [comment] 2019-01-30 19:30
> In other words, inside `lngPathCorrector`, just return` [as, query]` as though the default language is requested.

The trade-off of doing this is that if someone shares a locale-specific link for someone without a cookie, then they will be rerouted to the default language page instead.

Another option, if the user hasn't already specified a custom language detector, we can remove `headers` from the detectors and create our own custom language detector that inspects the headers and the path and decides what to do.

**Comment by capellini** [comment] 2019-01-30 23:12
> This is an issue that I specifically tracked down and fixed at some point in the past. 

Could the fix have been [the lines that I recently changed in `lng-path-corrector`](https://github.com/isaachinman/next-i18next/blob/ae8a98eb11d536224d0e69035b4a481d808096ee/src/utils/lng-path-corrector.js#L5-L7)?

> We _are not supporting regional locales_ at this time. We need to substring the first two chars of a locale - checking against `allLanguages` is not good enough, we'd miss `en-GB` even if we support `en`.

Unfortunately, I don't think that taking the substring will fix the problem, either, in this case.  Because it all depends on what the _client_ has configured to send in their `accept-language` headers (though it would work for me in the example, because my browser's `accept-language` headers are set to `en-US`, which is an acceptable language in our example if you take the first two letters).

Browser users can set their `accept-language` header to be whatever they want (e.g. 'zh') and currently, if it's not in `allLanguages` (even the first two characters), the error will be thrown.  It seems that if we don't set a `config.whitelist`, that tells `i18next` that any language code is acceptable.

> That doesn't explain why @vimutti77 is only seeing it 3/8 times.

I think he's seeing it 3/8 times because it's a race condition.  Whatever the last call to `changeLanguage` might be - sometimes it's 'en' and others we don't get a chance to `changeLanguage` fast enough in our code, so it winds up `en-US`. If he did it another 8 times, he may not see it at all, or he may see it more frequently.

**Comment by deshario** [comment] 2019-01-31 04:05
Use `fallbackLng: 'en' ` to set initial language ... It's not the good way but it works for me

``` 
const options = {
    localePath: 'client/static/locales',
    fallbackLng: 'en',
    defaultLanguage: 'th', // Not working
    otherLanguages: ['en','th'],
}

module.exports = new NextI18Next(options)

**Comment by isaachinman** [comment] 2019-02-01 16:44
> Could the fix have been the lines that I recently changed in lng-path-corrector?

Yes, that looks like it could be related. I think we need to set a whitelist which is equal to `allLanguages`. I remember looking into this previously and am surprised that's not already the case.

> it's a race condition

What is? Who's calling `changeLanguage`?

**Comment by capellini** [comment] 2019-02-01 19:44
> I think we need to set a whitelist which is equal to `allLanguages`.

That was my initial inclination.  If we set `options.whitelist` to `allLanguages` and set `options.load` to `'currentOnly'`, then `i18next` will ignore regional locales and only return 2-letter language codes. The problem is that, if we do this and the `i18next` language detectors cannot find a language and there is no `fallbackLng`, `i18next` never attempts to load any languages and `i18n.languages` becomes an empty array.

I got things to work by doing the following:
1. Ensure that `fallbackLng` is an array
2. `config.whitelist = config.allLanguages`
3. `config.load = 'currentOnly'`
4. Ensure that `req.i18n.languages` is an array in `lng-from-req` before we proceed with the `find` operation -- if it is not, use `defaultLanguage`

> What is? Who's calling `changeLanguage`?

`i18next-express-middleware` is calling [it here](https://github.com/i18next/i18next-express-middleware/blob/20c84267cf16da28bc14ca48ae9c044a46c21003/src/index.js#L50). (Incidentally, I think that we should enforce that fallbackLng is a list -- it seems looking through various `i18next` packages that this is the safest thing to do).  We then [subsequently call it in `appWithTranslation`](https://github.com/isaachinman/next-i18next/blob/0c340d53eea5f60819b7eba3cd1d3a23d90ac71b/src/hocs/app-with-translation.js#L58).  And it's also called in the `i18NextProvider`.

**Comment by isaachinman** [comment] 2019-02-04 17:51
> I got things to work by doing the following

@capellini Where are those changes? I will pick this up unless you have a PR open.

**Comment by capellini** [comment] 2019-02-04 18:06
I have them incorporated on a local repo.  If you want me to create a PR, just let me know.  Otherwise, feel free to open one.  Thanks.

**Comment by capellini** [comment] 2019-02-05 04:14
@isaachinman I thought that I would offer up my proposed solution in #156, if you'd like to see it.  Feel free to close it if you already have something in the works.

**Comment by isaachinman** [comment] 2019-02-05 20:04
@capellini I'm not really understanding everything there.

1. Why do you think changing `config.load` is necessary?
2. Why do you want to make `fallbackLng` an array? It should never be `undefined` in prod, but otherwise it should be fine as a string.

> 4. Ensure that `req.i18n.languages` is an array in `lng-from-req`

This is backwards. We should instead focus on how to inform i18next which languages _it_ can choose from, instead of us performing this work.

**Comment by capellini** [comment] 2019-02-06 00:51
> * Why do you think changing `config.load` is necessary?

If we're only supporting 2-letter codes, then this will prevent the LanguageDetectors from returning codes with regional locales and, since we are not supporting regional locales, we never run the risk of a regional locale being passed to us as valid.

If we don't set `load` and our `whitelist` is, say, `['en', 'de']`, then `i18next` will attempt to set any and all language codes that _start_ with `'en'` or `'de'`, even those with regional locale codes.

> Why do you want to make `fallbackLng` an array? It should never be `undefined` in prod, but otherwise it should be fine as a string.

In browsing the `i18next` source, this seems to be their convention as well (i.e. convert to an array, if string).  But more importantly, it will help prevent our code from breaking on [this line of `i18next-express-middleware`](https://github.com/i18next/i18next-express-middleware/blob/20c84267cf16da28bc14ca48ae9c044a46c21003/src/index.js#L50), which it currently does if `lng` is undefined..

> This is backwards. We should instead focus on how to inform i18next which languages _it_ can choose from, instead of us performing this work.

Do we need a custom language detector then?  Otherwise, if `i18next` cannot infer the language from it's built-in language detectors, `i18n.languages` is undefined (when we define a `whitelist`, that is).

It's also probably best if we change our simple example to use languages that aren't in our browser's `accept-language` headers.  I'm guessing that, since you're in the UK and I'm in the US, we both have `'en'` listed somewhere in our browsers' `accept-language` headers, which means that these bugs aren't apparent to us, as the built-in LanguageDetector that inspects the headers always chooses `'en'` for us, even if it finds nothing in the cookie.

**Comment by isaachinman** [comment] 2019-02-06 14:10
> If we're only supporting 2-letter codes, then this will prevent the LanguageDetectors from returning codes with regional locales

That is incorrect. Check out [the docs](https://www.i18next.com/overview/configuration-options). The setting we want is `languageOnly`, and that's what we [already have](https://github.com/isaachinman/next-i18next/blob/master/src/config/default-config.js#L11). Unless I'm misunderstanding you?

> this seems to be their convention as well

Again, as per the [docs](https://www.i18next.com/overview/configuration-options), `fallbackLng` is a string. We shouldn't change any i18next config options - our version of those options should be identical.

> if `i18next` cannot infer the language from it's built-in language detectors, `i18n.languages` is undefined

Isn't that the entire point of the `fallbackLanguage`, though? We should keep `fallbackLanguage` a string, but it should never be `undefined` in production.

**Comment by capellini** [comment] 2019-02-06 15:29
I have looked at the docs.

1. The `load`config option tells the language detector what codes are valid.  If you match on `languageOnly` you are telling the language detector that any variant of your acceptable codes in `whitelist` in which the language matches will suffice (i.e. as long as the `languageOnly` matches, then it's a good code).  So, for example, if 'en-US' is on your `whitelist` (_yes_ I know we don't support regional locales, but please bear with me), then any code that begins with `'en'` is valid, to include `'en'`, `'en-GB'`, etc.  That also means that if your `whitelist` contains `'en'`, then all codes that begin with '`en`' are acceptable, to include codes with regional locales.  [This is why we are seeing 'en-US' being set in this comment](https://github.com/isaachinman/next-i18next/issues/137#issuecomment-458989087).

    Instead, if you specify, 'currentOnly` the only acceptable codes are the ones that match your `whitelist` exactly.  That means that, if 'en' is in your whitelist, then 'en' is the only acceptable code -- any code with a regional locale is not accepted as valid by the language detectors.

2. Let's put aside that there's an apparent bug in `i18next-express-middleware` on the aforementioned line in their code (where they assume that `fallbackLng` is an array) which causes our code to break if we properly set `whitelist` and `load`.  According to [the docs specific to `fallbackLng`](https://www.i18next.com/principles/fallback#fallback-language), it can be a string, an array, or an object. In the code for `i18next`, you often see them converting `fallbackLng` to an array, if it is a string.  In fact, despite the docs that you reference saying that the default value for `fallbackLng` is the string `dev`, [look at how they set that default value in their code](https://github.com/i18next/i18next/blob/270904f6369ee9bbda059c3186fcea7baf9eb15d/src/defaults.js#L8) -- __as an array__.

3. Yes, in production, we set `fallbackLng` and, so, everything works in production. But if we set a `whitelist` and properly set `load` to 'currentOnly', our code will break for anyone who is developing using `next-i18next` because we do not set a `fallbackLng` in development.

**Comment by isaachinman** [comment] 2019-02-06 15:33
Okay, sounds like you've got a better grasp on it than I do at the moment. Thank you very much for all this info, and please bear with me - I'll need to set aside some time to review this and catch up properly.

**Comment by isaachinman** [comment] 2019-02-06 19:27
> the only acceptable codes are the ones that match your

@capellini Where did you see this? I cannot find detailed descriptions in the main docs.

**Comment by isaachinman** [comment] 2019-02-06 19:37
I am quite sure that `languageOnly` is indeed what we want. I do see the cookie being momentarily set to `en-GB` (in my case) and will look into that.

**Comment by isaachinman** [comment] 2019-02-06 19:55
Couple things here:

1. [This line](https://github.com/i18next/i18next-express-middleware/blob/20c84267cf16da28bc14ca48ae9c044a46c21003/src/index.js#L50) in `i18next-express-middleware` was breaking because we were setting `fallbackLng` to `null`, when we should have been setting it to `false` to achieve the desired effect of no fallback language.
2. `languageOnly` with a `whitelist` is exactly what we want. With that combination and a different lang header, `req.i18n.languages` is `undefined`, and we can set our fallback accordingly inside `lng-from-req`.

I'm taking care of these changes now.

**Comment by isaachinman** [comment] 2019-02-06 20:02
@jamuhl Do these `languageOnly` and `whitelist` options not get fed into the language detector from `i18next-express-middleware`?

**Comment by capellini** [comment] 2019-02-06 20:20
1. we enter `i18next-express-middleware`'s `handle`.  `req.lng` is undefined.  [This line](https://github.com/i18next/i18next-express-middleware/blob/20c84267cf16da28bc14ca48ae9c044a46c21003/src/index.js#L40) causes us to look use the `i18next.services.languageDetector.detect` method to search for the correct language.
2. Search for the language in the cookie -> it's not there
3. Search for the language in the headers:
    1. [Go to the lookup method for the header language detector](https://github.com/i18next/i18next-express-middleware/blob/20c84267cf16da28bc14ca48ae9c044a46c21003/src/LanguageDetector.js#L55) (for me, `accept-language` == `"en-US,en;q=0.9"`
    2. [In the code](https://github.com/i18next/i18next-express-middleware/blob/20c84267cf16da28bc14ca48ae9c044a46c21003/src/languageLookups/header.js#L4-L38), with my headers returns `['en-US', 'en']`.
    3. [Now check to see if the languages are whitelisted](https://github.com/i18next/i18next-express-middleware/blob/20c84267cf16da28bc14ca48ae9c044a46c21003/src/LanguageDetector.js#L64), the first one that is acceptable will be the language that we select.

[Looking inside the code of `isWhitelisted`](https://github.com/i18next/i18next/blob/3b31cf35beb71f4068e0a6831d133b58e09a7a2e/src/LanguageUtils.js#L61-L66):
- Let's check to see if `en-US` is whitelisted:
    -  `options.load === 'languageOnly'`, so `getLangaugePartFromCode` => code now == 'en'
    - `'en'` code is in our `whitelist`, so `'en-US'` is a good code 

Therefore, set the cookie to `'en-US'`

**Comment by capellini** [comment] 2019-02-06 20:33
> we should have been setting it to `false` to achieve the desired effect of no fallback language.

I learned something today: `typeof false[0] === 'undefined'` :smile:, so yes - this would work just as well as an empty array.  And given that you seem to be dead set against using an array, using `false` will do, indeed.

**Comment by isaachinman** [comment] 2019-02-06 20:34
@capellini I don't think I quite followed that without further explanation, but I am hoping #165 fixes the problem here. On that branch, if I hit `localhost:3000` in an incognito window with my headers set to Polish _or_ `en-GB`, I get back: `Cookie: i18next=en`.

Do you mind taking a look at the PR and seeing if it solves the issues you saw?

**Comment by isaachinman** [comment] 2019-02-06 20:40
Ah, I just saw `false` in the i18next docs:

![screen shot 2019-02-06 at 20 40 11](https://user-images.githubusercontent.com/10575782/52372196-6b26d200-2a4f-11e9-8665-7b5b43fbdbdf.png)

Wasn't aware anything tricky was going on!

**Comment by capellini** [comment] 2019-02-06 22:20
It "works", but it does so like this (server-side, using the same accept-language headers as I had before):
1. because `config.load === 'languageOnly'`, `i18next-express-middleware` sets `req.lng = 'en-US'`, `req.language = 'en-US'`, and `req.languages = ['en']`
2. [In `appWithTranslation`](https://github.com/isaachinman/next-i18next/blob/9ce27d2788ef9d5dc08629ee0d4445d2b00436bc/src/hocs/app-with-translation.js#L55-L58), our call to `lngFromReq` returns `'en'` and we set the language to `'en'`

However, req.lng is initially set to `'en-US'` server-side.  Therefore, anyone with an accept language of `'en-*'`, even if they don't have `'en'` in their accept-language header, will have their language set to `'en'`

On the other hand, if `load === 'currentOnly'`, `'en'` will only be set if it is explicitly in `'whitelist'` and listed in the accept-language header.

> I don't think I quite followed that without further explanation

The key is in[ `isWhitelisted`](https://github.com/i18next/i18next/blob/3b31cf35beb71f4068e0a6831d133b58e09a7a2e/src/LanguageUtils.js#L61-L66), which determines if we will accept a given code.
```js
  isWhitelisted(code) {
    if (this.options.load === 'languageOnly' || this.options.nonExplicitWhitelist) {
      code = this.getLanguagePartFromCode(code);
    }
    return !this.whitelist || !this.whitelist.length || this.whitelist.indexOf(code) > -1;
  }
```
Given:
1. `code === 'en-US`'
2. `config.whitelist === ['en']`
3. 'config.load === 'languageOnly'`
4. `getLanguagePartFromCode('en-US') === 'en'`

Then, since `config.load === 'languageOnly'`, then we `getLanguagePartFromCode('en-US')`.

Now `code === 'en'`.  Since `'en'` is in our `whitelist`, `isWhitelisted` returns `true`.  Therefore, `'en-US'` is a valid code when `config.load === 'languageOnly'`.

**Comment by isaachinman** [comment] 2019-02-07 22:02
> Therefore, anyone with an accept language of `'en-*'`, even if they don't have `'en'` in their accept-language header, will have their language set to `'en'`

Isn't that exactly the desired behaviour? My understanding of i18next is that `req.languages` is the relevant bit here for us, not `req.lng`.

**Comment by capellini** [comment] 2019-02-07 23:58
If you [do not want `changeLanguage('en-US')` to be called](https://github.com/i18next/i18next-express-middleware/blob/20c84267cf16da28bc14ca48ae9c044a46c21003/src/index.js#L50), and therefore want to assert that [`allLanguages.includes(currentLanguage)`](https://github.com/isaachinman/next-i18next/blob/b5b515ea78b0421197b855e8ddd7c865da10bde4/src/utils/lng-path-corrector.js#L6) when a [language change occurs](https://github.com/isaachinman/next-i18next/blob/b5b515ea78b0421197b855e8ddd7c865da10bde4/src/hocs/app-with-translation.js#L20), then you cannot do so while `config.load === 'languageOnly'`. 

If the intended behavior is for someone who prefers `'en-US'` to have their language set to `'en'`, and to not support a `whitelist` that has regional locales, then you can assert something like `allLanguages.includes(currentLanguage.slice(0, 2))`.  However, in practice, users' accept-language headers that contain `'en-US'` will most likely also include `'en'` somewhere in it, as well.

Setting `config.load = 'currentOnly'` ensures that `allLanguages` will always include `currentLanguage` and that the only languages that we attempt to use are the ones that are on our `whitelist`.

**Comment by isaachinman** [comment] 2019-02-09 14:32
@capellini I updated #165. Can you take a look? I am most likely going to merge this later today unless you see any issues with it. Thank you for your help on this one.

**Closed** 2019-02-09 18:05 UTC

**Comment by capellini** [comment] 2019-02-09 20:39
@isaachinman Sorry - just getting to this now.  I believe that's all that was needed.  You're most welcome.
