### ISSUE TITLE
how to change language ?

### ISSUE THREAD

**Issue by nightwolf-041** [isaachinman/next-i18next#1309] opened 2021-07-10 12:02 UTC
hi,
i'm trying to change language 
but changeLanguage method dose not work 
what is the solution ?
here is my code 

```
  const { t, i18n } = useTranslation('common');
  
  useEffect(() => {
     i18n.changeLanguage('fa');
  }, [])
```

**Comment by isaachinman** [comment] 2021-07-10 12:06
Duplicate of many previous issues, please search before opening new issues. Good luck!

**Closed by isaachinman** 2021-07-10 12:06 UTC

**Comment by nightwolf-041** [comment] 2021-07-10 12:14
yes i see this thank you
but i want to know is that possible to change locales without change URL ? 
like :
example.com/fa
example.com/en 

any way to remove them ?

**Comment by isaachinman** [comment] 2022-02-22 14:39
Localised routing is handled by NextJs directly. Any related requests should go to the Vercel team.
