### ISSUE TITLE
Unable to contribute

### ISSUE THREAD

**Issue by prokopsimek** [isaachinman/next-i18next#234] opened 2019-03-15 10:15 UTC
## Describe the bug
I would like to contribute on the project, but the pre-commit fails.

## Occurs in next-i18next version
`master`

## Steps to reproduce
https://github.com/isaachinman/next-i18next/pull/233

## Expected behaviour
I expected that the `git commit` works, if I change only typings :D 

## Screenshots
```
✔ ~/Sites/_contribs/next-i18next [feature/withNamespacesTypings L|●1] 
11:00 $ git commit -m "feat(types): add return type for withNamespaces function"
husky > pre-commit (node v8.15.0)
yarn run v1.13.0
$ eslint src examples __tests__
✨  Done in 3.72s.
yarn run v1.13.0
$ yarn build:example && NODE_ENV=test jest --maxWorkers=1 --silent
$ cd examples/simple && yarn build
$ next build

● Client █████████████████████████ chunk asset optimization (92%) TerserPlugin 
 

✖ Server
  Compiled with some errors in 3.12s


✖ Client
  Compiled with some errors in 3.43s

✖ Server
  Compiled with some errors in 3.12s

ModuleNotFoundError: Module not found: Error: Can't resolve 'next-i18next/dist/commonjs' in '/Users/prokop/Sites/_contribs/next-i18next/examples/simple'
    at factory.create (/Users/prokop/Sites/_contribs/next-i18next/node_modules/webpack/lib/Compilation.js:823:10)
    at factory (/Users/prokop/Sites/_contribs/next-i18next/node_modules/webpack/lib/NormalModuleFactory.js:397:22)
    at resolver (/Users/prokop/Sites/_contribs/next-i18next/node_modules/webpack/lib/NormalModuleFactory.js:130:21)
    at asyncLib.parallel (/Users/prokop/Sites/_contribs/next-i18next/node_modules/webpack/lib/NormalModuleFactory.js:224:22)
    at /Users/prokop/Sites/_contribs/next-i18next/node_modules/neo-async/async.js:2825:7
    at /Users/prokop/Sites/_contribs/next-i18next/node_modules/neo-async/async.js:6886:13
    at normalResolver.resolve (/Users/prokop/Sites/_contribs/next-i18next/node_modules/webpack/lib/NormalModuleFactory.js:214:25)
    at doResolve (/Users/prokop/Sites/_contribs/next-i18next/node_modules/enhanced-resolve/lib/Resolver.js:184:12)
    at hook.callAsync (/Users/prokop/Sites/_contribs/next-i18next/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
    at _fn0 (eval at create (/Users/prokop/Sites/_contribs/next-i18next/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:15:1)
    at resolver.doResolve (/Users/prokop/Sites/_contribs/next-i18next/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:37:5)
    at hook.callAsync (/Users/prokop/Sites/_contribs/next-i18next/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
    at _fn0 (eval at create (/Users/prokop/Sites/_contribs/next-i18next/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:15:1)
    at hook.callAsync (/Users/prokop/Sites/_contribs/next-i18next/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
    at _fn0 (eval at create (/Users/prokop/Sites/_contribs/next-i18next/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:12:1)
    at resolver.doResolve (/Users/prokop/Sites/_contribs/next-i18next/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:42:38)
resolve 'next-i18next/dist/commonjs' in '/Users/prokop/Sites/_contribs/next-i18next/examples/simple'
  Parsed request is a module
  using description file: /Users/prokop/Sites/_contribs/next-i18next/examples/simple/package.json (relative path: .)
    Field 'browser' doesn't contain a valid alias configuration
    resolve as module
      /Users/prokop/Sites/_contribs/next-i18next/examples/node_modules doesn't exist or is not a directory
      /Users/prokop/Sites/_contribs/node_modules doesn't exist or is not a directory
      /Users/prokop/Sites/node_modules doesn't exist or is not a directory
      /Users/prokop/node_modules doesn't exist or is not a directory
      /Users/node_modules doesn't exist or is not a directory
      /node_modules doesn't exist or is not a directory
      looking for modules in /Users/prokop/Sites/_contribs/next-i18next/examples/simple/node_modules
        using description file: /Users/prokop/Sites/_contribs/next-i18next/examples/simple/package.json (relative path: ./node_modules)
          Field 'browser' doesn't contain a valid alias configuration
      looking for modules in /Users/prokop/Sites/_contribs/next-i18next/node_modules
        using description file: /Users/prokop/Sites/_contribs/next-i18next/package.json (relative path: ./node_modules)
          Field 'browser' doesn't contain a valid alias configuration
          using description file: /Users/prokop/Sites/_contribs/next-i18next/examples/simple/package.json (relative path: ./node_modules/next-i18next/dist/commonjs)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
          using description file: /Users/prokop/Sites/_contribs/next-i18next/package.json (relative path: ./node_modules/next-i18next/dist/commonjs)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              /Users/prokop/Sites/_contribs/next-i18next/examples/simple/node_modules/next-i18next/dist/commonjs doesn't exist
            .wasm
              Field 'browser' doesn't contain a valid alias configuration
              /Users/prokop/Sites/_contribs/next-i18next/node_modules/next-i18next/dist/commonjs doesn't exist
            .wasm
              Field 'browser' doesn't contain a valid alias configuration
              /Users/prokop/Sites/_contribs/next-i18next/examples/simple/node_modules/next-i18next/dist/commonjs.wasm doesn't exist
            .mjs
              Field 'browser' doesn't contain a valid alias configuration
              /Users/prokop/Sites/_contribs/next-i18next/node_modules/next-i18next/dist/commonjs.wasm doesn't exist
            .mjs
              Field 'browser' doesn't contain a valid alias configuration
              /Users/prokop/Sites/_contribs/next-i18next/examples/simple/node_modules/next-i18next/dist/commonjs.mjs doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              /Users/prokop/Sites/_contribs/next-i18next/node_modules/next-i18next/dist/commonjs.mjs doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              /Users/prokop/Sites/_contribs/next-i18next/examples/simple/node_modules/next-i18next/dist/commonjs.js doesn't exist
            .jsx
              Field 'browser' doesn't contain a valid alias configuration
              /Users/prokop/Sites/_contribs/next-i18next/node_modules/next-i18next/dist/commonjs.js doesn't exist
            .jsx
              Field 'browser' doesn't contain a valid alias configuration
              /Users/prokop/Sites/_contribs/next-i18next/examples/simple/node_modules/next-i18next/dist/commonjs.jsx doesn't exist
            .json
              Field 'browser' doesn't contain a valid alias configuration
              /Users/prokop/Sites/_contribs/next-i18next/node_modules/next-i18next/dist/commonjs.jsx doesn't exist
            .json
              Field 'browser' doesn't contain a valid alias configuration
              /Users/prokop/Sites/_contribs/next-i18next/examples/simple/node_modules/next-i18next/dist/commonjs.json doesn't exist
              /Users/prokop/Sites/_contribs/next-i18next/node_modules/next-i18next/dist/commonjs.json doesn't exist
            as directory
              /Users/prokop/Sites/_contribs/next-i18next/examples/simple/node_modules/next-i18next/dist/commonjs doesn't exist
            as directory
              /Users/prokop/Sites/_contribs/next-i18next/node_modules/next-i18next/dist/commonjs doesn't exist
ModuleNotFoundError: Module not found: Error: Can't resolve 'next-i18next/dist/commonjs' in '/Users/prokop/Sites/_contribs/next-i18next/examples/simple'
    at factory.create (/Users/prokop/Sites/_contribs/next-i18next/node_modules/webpack/lib/Compilation.js:823:10)
    at factory (/Users/prokop/Sites/_contribs/next-i18next/node_modules/webpack/lib/NormalModuleFactory.js:397:22)
    at resolver (/Users/prokop/Sites/_contribs/next-i18next/node_modules/webpack/lib/NormalModuleFactory.js:130:21)
    at asyncLib.parallel (/Users/prokop/Sites/_contribs/next-i18next/node_modules/webpack/lib/NormalModuleFactory.js:224:22)
    at /Users/prokop/Sites/_contribs/next-i18next/node_modules/neo-async/async.js:2825:7
    at /Users/prokop/Sites/_contribs/next-i18next/node_modules/neo-async/async.js:6886:13
    at normalResolver.resolve (/Users/prokop/Sites/_contribs/next-i18next/node_modules/webpack/lib/NormalModuleFactory.js:214:25)
    at doResolve (/Users/prokop/Sites/_contribs/next-i18next/node_modules/enhanced-resolve/lib/Resolver.js:184:12)
    at hook.callAsync (/Users/prokop/Sites/_contribs/next-i18next/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
    at _fn0 (eval at create (/Users/prokop/Sites/_contribs/next-i18next/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:15:1)
    at resolver.doResolve (/Users/prokop/Sites/_contribs/next-i18next/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:37:5)
    at hook.callAsync (/Users/prokop/Sites/_contribs/next-i18next/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
    at _fn0 (eval at create (/Users/prokop/Sites/_contribs/next-i18next/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:15:1)
    at hook.callAsync (/Users/prokop/Sites/_contribs/next-i18next/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
    at _fn0 (eval at create (/Users/prokop/Sites/_contribs/next-i18next/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:12:1)
    at resolver.doResolve (/Users/prokop/Sites/_contribs/next-i18next/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:42:38)
resolve 'next-i18next/dist/commonjs' in '/Users/prokop/Sites/_contribs/next-i18next/examples/simple'
  Parsed request is a module
  using description file: /Users/prokop/Sites/_contribs/next-i18next/examples/simple/package.json (relative path: .)
    resolve as module
      /Users/prokop/Sites/_contribs/next-i18next/examples/node_modules doesn't exist or is not a directory
      /Users/prokop/Sites/_contribs/node_modules doesn't exist or is not a directory
      /Users/prokop/Sites/node_modules doesn't exist or is not a directory
      /Users/prokop/node_modules doesn't exist or is not a directory
      /Users/node_modules doesn't exist or is not a directory
      /node_modules doesn't exist or is not a directory
      looking for modules in /Users/prokop/Sites/_contribs/next-i18next/examples/simple/node_modules
        using description file: /Users/prokop/Sites/_contribs/next-i18next/examples/simple/package.json (relative path: ./node_modules)
          using description file: /Users/prokop/Sites/_contribs/next-i18next/examples/simple/package.json (relative path: ./node_modules/next-i18next/dist/commonjs)
            no extension
              /Users/prokop/Sites/_contribs/next-i18next/examples/simple/node_modules/next-i18next/dist/commonjs doesn't exist
      looking for modules in /Users/prokop/Sites/_contribs/next-i18next/node_modules
        using description file: /Users/prokop/Sites/_contribs/next-i18next/package.json (relative path: ./node_modules)
          using description file: /Users/prokop/Sites/_contribs/next-i18next/package.json (relative path: ./node_modules/next-i18next/dist/commonjs)
            no extension
              /Users/prokop/Sites/_contribs/next-i18next/node_modules/next-i18next/dist/commonjs doesn't exist
            .wasm
              /Users/prokop/Sites/_contribs/next-i18next/examples/simple/node_modules/next-i18next/dist/commonjs.wasm doesn't exist
            .wasm
              /Users/prokop/Sites/_contribs/next-i18next/node_modules/next-i18next/dist/commonjs.wasm doesn't exist
            .js
              /Users/prokop/Sites/_contribs/next-i18next/examples/simple/node_modules/next-i18next/dist/commonjs.js doesn't exist
            .js
              /Users/prokop/Sites/_contribs/next-i18next/node_modules/next-i18next/dist/commonjs.js doesn't exist
            .mjs
              /Users/prokop/Sites/_contribs/next-i18next/examples/simple/node_modules/next-i18next/dist/commonjs.mjs doesn't exist
            .mjs
              /Users/prokop/Sites/_contribs/next-i18next/node_modules/next-i18next/dist/commonjs.mjs doesn't exist
            .jsx
              /Users/prokop/Sites/_contribs/next-i18next/examples/simple/node_modules/next-i18next/dist/commonjs.jsx doesn't exist
            .jsx
              /Users/prokop/Sites/_contribs/next-i18next/node_modules/next-i18next/dist/commonjs.jsx doesn't exist
            .json
              /Users/prokop/Sites/_contribs/next-i18next/examples/simple/node_modules/next-i18next/dist/commonjs.json doesn't exist
            .json
              /Users/prokop/Sites/_contribs/next-i18next/node_modules/next-i18next/dist/commonjs.json doesn't exist
            as directory
              /Users/prokop/Sites/_contribs/next-i18next/examples/simple/node_modules/next-i18next/dist/commonjs doesn't exist
            as directory
              /Users/prokop/Sites/_contribs/next-i18next/node_modules/next-i18next/dist/commonjs doesn't exist
> Build error occurred
Error: > Build failed because of webpack errors
    at Object.build [as default] (/Users/prokop/Sites/_contribs/next-i18next/node_modules/next/dist/build/index.js:69:15)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
```

## OS (please complete the following information)
 - MBP 2015 13" macOS Mojave v10.14.4 Beta
 - Default Google Chrome Version 72.0.3626.121 (Official Build) (64-bit)

**Comment by prokopsimek** [comment] 2019-03-15 10:18
After that, I used Github UI to change the source code.

**Comment by isaachinman** [comment] 2019-03-15 11:14
Sort of a duplicate of #230. You need to build the source first. See also this comment: https://github.com/isaachinman/next-i18next/issues/220#issuecomment-471028160.

**Closed by isaachinman** 2019-03-15 11:14 UTC
