### ISSUE TITLE
Can't resolve core-js/modules/es7.symbol.async-iterator

### ISSUE THREAD

**Issue by andylacko** [isaachinman/next-i18next#129] opened 2019-01-27 19:55 UTC
Hello, I have seen that subpaths were merged, nice 👌 Although I see error :/

 Can't resolve 'core-js/modules/es7.symbol.async-iterator' in '/Users/andy/Workspace/js/medialer/node_modules/next-i18next/dist/utils'

I am on node v11.8.0, it happened after I updated to v0.23.0

**Comment by andylacko** [comment] 2019-01-27 19:58
noticed there is no utils folder in package installed with NPM, after trying to build it manually it says

src doesn't exist `babel src --out-dir dist`

**Comment by andylacko** [comment] 2019-01-27 20:06
forgot to install peer dependency i18next...

**Comment by isaachinman** [comment] 2019-01-27 20:10
Hi @andylacko, do you mean that you have to do something more than just `yarn add next-i18next`? Shouldn't peer deps install automatically?

**Comment by andylacko** [comment] 2019-01-27 20:13
I removed packages, then reinstalled and npm wrote few WARNs, and one of them was that I have to install **i18next** manually, installed and it was working, dunno, if something is with my package.json or it is mistake in dep config in this lib.

If you want to check just reinstall packages and see if if it is specific to my setup, or not

**Comment by lucasfeliciano** [comment] 2019-01-28 08:57
Got the same here today when installed the last version of `next-i18next`
🤔

**Comment by isaachinman** [comment] 2019-01-28 09:13
So, I believe the `es7.symbol.async-iterator` thing is from Babel.

@capellini Are you sure this is related to v0.23.0? What version are you upgrading from? Let's try to narrow the problem down to a specific release.

**Comment by isaachinman** [comment] 2019-01-28 09:13
Could be related to https://github.com/isaachinman/next-i18next/commit/9c96479e27297e300d04b62b17db3d3aa80ae4c4.

**Comment by lucasfeliciano** [comment] 2019-01-28 09:20
Indeed, however if I install with `yarn` it resolves the dependency.

I think this only happens with `npm` can you confirm?

**Comment by capellini** [comment] 2019-01-28 10:55
I ran across this comment in [the babel docs for useBuiltins](https://babeljs.io/docs/en/next/babel-preset-env.html#usebuiltins):

> You may need to specify core-js@2 as a top level dependency in your application if there isn't a core-js dependency or there are multiple versions.

It looks like we may need to pin core-js@2. However, I can't reproduce this, and I use `npm`.

@andylacko , would you mind posting your `'dependencies'` and `'devDependencies'` from your `package.json`?  Then, I might be able to create a project that could replicate this issue.

**Comment by andylacko** [comment] 2019-01-28 11:03
```
npm WARN deprecated kleur@2.0.2: Please upgrade to kleur@3 or migrate to 'ansi-colors' if you prefer the old syntax. Visit <https://github.com/lukeed/kleur/releases/tag/v3.0.0\> for migration path(s).

> fsevents@1.2.7 install /Users/andy/Workspace/js/next-i18next/node_modules/fsevents
> node install

node-pre-gyp WARN Using request for node-pre-gyp https download 
[fsevents] Success: "/Users/andy/Workspace/js/next-i18next/node_modules/fsevents/lib/binding/Release/node-v67-darwin-x64/fse.node" is installed via remote

> husky@1.3.1 install /Users/andy/Workspace/js/next-i18next/node_modules/husky
> node husky install

husky > setting up git hooks
husky > done

> puppeteer@1.11.0 install /Users/andy/Workspace/js/next-i18next/node_modules/puppeteer
> node install.js

Downloading Chromium r609904 - 82.7 Mb [====================] 100% 0.0s 
Chromium downloaded to /Users/andy/Workspace/js/next-i18next/node_modules/puppeteer/.local-chromium/mac-609904

> next-i18next@0.23.0 prepare /Users/andy/Workspace/js/next-i18next
> yarn build

sh: yarn: command not found
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! next-i18next@0.23.0 prepare: `yarn build`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the next-i18next@0.23.0 prepare script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/andy/.npm/_logs/2019-01-28T10_47_39_788Z-debug.log

```

after installing `npm i -g yarn` it succeeded


so the problem is, I have no yarn installed, in package.json, there are some yarn calls, I think, this is the issue

**Comment by isaachinman** [comment] 2019-01-28 18:30
> However, I can't reproduce this, and I use npm

@capellini Probably because you don't have a conflicting dep and @andylacko does. Thanks for finding that info in the docs.

@andylacko I've added `core-js` as an explicit dep and published v0.23.1. Can you let me know if this resolves the issue.

**Comment by capellini** [comment] 2019-01-28 18:40
> Probably because you don't have a conflicting dep and @andylacko does

Yes, specifically `draft-js@^0.10.5`

![screenshot from 2019-01-28 06-46-32](https://user-images.githubusercontent.com/75311/51858124-ef67af80-2301-11e9-91a1-3f65bcecd157.png)

We may be able to get away with just specifying `core-js@^2.5.0` as a dependency.  But, assuming that `next-i18next` is a top-level dependency, a peer dependency is technically the best way to specify this, as the correct version of `core-js` would also be at the top-level.

@isaachinman - It may be better to:
1. make `core-js` a peer dependency with the lowest compatible version possible (`core-js@^2.5.0`) 
2. move the `@babel/polyfill` to dev dependencies
3. add `core-js@^2.5.0` to dev dependencies

This will put the onus of determining which version of `core-js`/`@babel/polyfill` to use on the user.  Keeping it as a dev dependency on our project allows us to still use it for development, as needed.  Of course, then users would have to install `core-js` on their own (and manually resolving peer dependencies can be a pain, at times). So instead of `npm install/yarn add next-i18next`, they would have to `npm install/yarn add next-i18next core-js@^2.5`.

Considering the way that `@babel/polyfill` works, I _think_ the peer dependency is the only real way to fix this.

**Comment by isaachinman** [comment] 2019-01-28 18:42
I follow the bit about moving `core-js` to a peer, but not about moving `@babel/polyfill` to a dev dep. How does that help? To be clear, `@babel/polyfill` is used at runtime.

**Comment by capellini** [comment] 2019-01-28 19:34
> `@babel/polyfill` is used at runtime.

Ah, right.  Then it wouldn't make sense to move it to a dev dependency.  Would it then make sense to also have `@babel/polyfill` as a peer dependency only?

**Comment by isaachinman** [comment] 2019-01-28 19:44
> Would it then make sense to also have @babel/polyfill as a peer dependency only?

As far as I know, we don't depend on any specific version of `@babel/polyfill`. Moreover, I'm not even sure if we depend upon any specific version of `core-js`. This would be worth finding out.

The original problem in this issue is that `core-js` was absent entirely, I believe.

**Comment by capellini** [comment] 2019-01-28 20:11
> As far as I know, we don't depend on any specific version of `@babel/polyfill`.

No specific version, but we do have it as a dependency in our `package.json`.  If it's strictly used at runtime, can we just list it as a peer dep?

> Moreover, I'm not even sure if we depend upon any specific version of `core-js`.

In this case, since we evidently need `core-js/modules/es7.symbol.async-iterator` somewhere in our utils, we need to have `core-js@^2.5.0`.

> The original problem in this issue is that `core-js` was absent entirely, I believe.

When I installed a dummy project with the same dependencies as @andylacko, `core-js` was present in both the project root and in downstream package `node_modules` directories.

The problem was that the version of `core-js` that was referenced (the one in the project root) didn't have the `core-js/modules/es7.symbol.async-iterator` file.  I assume that @andylacko got past this by doing an `npm install core-js`, since the latest version is listed in his dependencies.

Using @andylacko's deps (except for the `core-js` dep), if you installed with `npm` the root version of `core-js` was at v1.2.7 because `draft-js` depended on `fbjs`, which in turn depended that version of `core-js`.  Then `@babel/polyfill`'s `node_modules` had `core-js@latest` because of several dependencies on it.

However, if you used `yarn` the root `node_modules` directory contained `core-js@latest` and `fbjs`'s `node_modules` contained `core-js` v1.2.7.

The different locations of `core-js` and which one is in the root of the project directory matters because when babel polyfills an async iterator, it replaces the line of code that uses an async interator with something like:
```js
import 'core-js/modules/es7.symbol.async-iterator';
// ... polyfilled code
```
And so node uses the `core-js` from the top of the project tree.  If the version that is found does not have the file we need, the above error is thrown.

Playing around with `yarn` and `npm` a bit more (with contrived examples), I also managed to get `npm` to install the latest version of `core-js` on the project root, but not `yarn` and also ran into a situation where they both did not install the latest version on project root.

**Comment by isaachinman** [comment] 2019-01-28 20:21
> can we just list it as a peer dep

Sure.

> we evidently need core-js/modules/es7.symbol.async-iterator somewhere in our utils, we need to have core-js@^2.5.0

OK.

I'm open to any sensible PRs on this, but we need to be very careful that we don't break installs outright. This package needs to work with the latest versions of `npm` and `yarn` equally well.

**Comment by capellini** [comment] 2019-01-29 03:08
I agree.  I'd like to take a little more time to research `npm` and `yarn` dependency resolution, peer dependencies, as well as `babel` and use of it with `next-i18next` different projects before I submit the PR.

@andylacko and @lucasfeliciano - the short-term fix is to install `core-js@^2.5.0` in your projects.  That should work, but please let me know if it doesn't.

Incidentally @lucasfeliciano, would you mind posting the output of `yarn why core-js` just so I can confirm that you're facing the same problem and not some other one?

**Comment by isaachinman** [comment] 2019-01-29 19:33
@capellini The short term fix was v0.23.1.

**Comment by isaachinman** [comment] 2019-01-30 20:15
@andylacko Can you please chime in and let us know if v0.23.1 fixed your issue?

If so, we'll close this issue in favour of #136 as a longer-term solution.

**Comment by andylacko** [comment] 2019-01-30 20:43
@isaachinman , it works 👌

**Comment by isaachinman** [comment] 2019-01-30 20:49
Excellent. We'll now close this and track a peer-deps solution via #136.

**Closed by isaachinman** 2019-01-30 20:49 UTC

**Comment by lucasfeliciano** [comment] 2019-02-05 09:02
@isaachinman after `v0.26.0` this is back for me 

![image](https://user-images.githubusercontent.com/968014/52262536-083d1a00-292d-11e9-8622-13ca07db364c.png)


Probably related to https://github.com/isaachinman/next-i18next/commit/4bf9d37c761d45f4a32f0845e9bc0fb5938fe3d4

**Comment by isaachinman** [comment] 2019-02-05 09:03
@lucasfeliciano Right. I need a way to reproduce. Instead of including `core-js`, we're going to _not_ polyfill. You're seeing this when doing installs via `npm`, right?

**Comment by lucasfeliciano** [comment] 2019-02-05 09:06
Correct, installing via npm. 
I think that is enough to reproduce if not let me know and I try to create a repo where this happens

**Comment by isaachinman** [comment] 2019-02-05 09:45
@lucasfeliciano Is that just dev, or prod too? I installed `next-i18next` in an empty dir and got it up and running without any issues.
