### ISSUE TITLE
useRouter access from next-i18next

### ISSUE THREAD

**Issue by jonathangiamp** [isaachinman/next-i18next#483] opened 2019-08-29 13:02 UTC
## Describe the bug
I'm not able to import **useRouter** from `next` while it's supposed to be exposes by `next-i18next`.

## Occurs in next-i18next version
Here my dependencies
```
{
  "express": "^4.16.4",
  "i18next": "^14.0.1",
  "next": "^9.0.3",
  "next-i18next": 1.1.2",
  "react": "16.9.0",
  "react-dom": "16.9.0"
}
```

## Steps to reproduce
[Here a codesandbox](https://codesandbox.io/s/next-i18next-userouter-5pety) with minimal configuration to reproduce the issue.

## Expected behaviour
As described from [nextjs documentation](https://nextjs.org/docs#userouter), **useRouter** is a hooks version of Router class.
> If you want to access the router object inside any component in your app, you can use the useRouter hook

As described from next-i18next documentation, `next-i18next` should shares the same API as the native Next Router. 
> The exported Router shares the same API as the native Next Router.

I expected to have access to **useRouter** hooks from i18n instance created by `next-i18next`.
```javascript
import { useRouter } from "../i18n"; // undefined
```

**Comment by isaachinman** [comment] 2019-08-29 13:10
Is this a duplicate of #316? I'd expect that work to be done at the same time. Contributions welcome.

**Comment by oswaldoacauan** [comment] 2019-09-09 14:22
Any news on this one?

**Comment by fernandobandeira** [comment] 2019-09-10 23:51
I think an implementation idea would be to do the exact thing that nextjs is doing, so basically.

Start by creating a context for the router instance: https://github.com/zeit/next.js/blob/canary/packages/next/next-server/lib/router-context.ts

Wrap the app with this context, we can do that inside the `appWithTranslation`, we already have the router available there, we can call our wrapper there and pass it to the context provider.
https://github.com/zeit/next.js/blob/canary/packages/next/client/index.js#L309

`withRouter` will simply use the context and pass the router as a prop to the composed component:
https://github.com/zeit/next.js/blob/canary/packages/next/client/with-router.tsx

`useRouter` just returns the result from `useContext`
https://github.com/zeit/next.js/blob/canary/packages/next/client/router.ts#L115

Doesn't seem too difficult, I don't have the time to open a PR right now though, let's discuss if this sounds like a good implementation plan, ping @capellini @isaachinman

**Comment by isaachinman** [comment] 2019-12-03 09:45
Going to close as a duplicate of #316. If anyone is interested in doing this work, please do let me know.

**Closed by isaachinman** 2019-12-03 09:45 UTC
